/**
 * Taboo cards: describe the word without saying it or any of the four
 * forbidden words. Everyday and exam-topic vocabulary, B1–C1.
 */

const C = (word, ...taboo) => ({ word, taboo });

const RAW = [
  C('hospital', 'doctor', 'sick', 'nurse', 'ill'),
  C('library', 'book', 'read', 'borrow', 'quiet'),
  C('airport', 'plane', 'fly', 'ticket', 'travel'),
  C('umbrella', 'rain', 'wet', 'open', 'weather'),
  C('teacher', 'school', 'student', 'lesson', 'teach'),
  C('breakfast', 'morning', 'eat', 'meal', 'food'),
  C('birthday', 'cake', 'party', 'born', 'year'),
  C('mirror', 'see', 'face', 'glass', 'reflection'),
  C('passport', 'travel', 'country', 'document', 'border'),
  C('smartphone', 'call', 'phone', 'screen', 'apps'),
  C('pollution', 'air', 'dirty', 'environment', 'factory'),
  C('holiday', 'vacation', 'rest', 'travel', 'summer'),
  C('exam', 'test', 'student', 'pass', 'question'),
  C('salary', 'money', 'job', 'pay', 'month'),
  C('neighbour', 'next', 'door', 'house', 'live'),
  C('wedding', 'marry', 'bride', 'groom', 'party'),
  C('internet', 'online', 'web', 'computer', 'connection'),
  C('bicycle', 'ride', 'wheels', 'pedal', 'bike'),
  C('kitchen', 'cook', 'room', 'food', 'house'),
  C('climate', 'weather', 'temperature', 'change', 'hot'),
  C('volunteer', 'help', 'free', 'money', 'work'),
  C('advertisement', 'product', 'buy', 'TV', 'sell'),
  C('university', 'student', 'study', 'degree', 'college'),
  C('interview', 'job', 'question', 'answer', 'company'),
  C('traffic', 'cars', 'road', 'jam', 'slow'),
  C('museum', 'history', 'old', 'art', 'visit'),
  C('dentist', 'teeth', 'doctor', 'tooth', 'mouth'),
  C('homework', 'school', 'teacher', 'task', 'home'),
  C('grandmother', 'old', 'family', 'mother', 'grandfather'),
  C('snow', 'white', 'winter', 'cold', 'ice'),
  C('river', 'water', 'flow', 'sea', 'bridge'),
  C('bridge', 'river', 'cross', 'road', 'over'),
  C('desert', 'sand', 'hot', 'dry', 'Sahara'),
  C('mountain', 'high', 'climb', 'top', 'hill'),
  C('island', 'sea', 'water', 'surrounded', 'land'),
  C('electricity', 'power', 'light', 'energy', 'wire'),
  C('vegetables', 'carrot', 'healthy', 'green', 'eat'),
  C('newspaper', 'read', 'news', 'paper', 'journalist'),
  C('journalist', 'news', 'write', 'newspaper', 'report'),
  C('taxi', 'car', 'driver', 'pay', 'yellow'),
  C('restaurant', 'eat', 'food', 'waiter', 'menu'),
  C('waiter', 'restaurant', 'food', 'serve', 'order'),
  C('password', 'secret', 'login', 'account', 'word'),
  C('friendship', 'friend', 'trust', 'close', 'people'),
  C('success', 'win', 'goal', 'achieve', 'fail'),
  C('happiness', 'happy', 'smile', 'joy', 'feel'),
  C('freedom', 'free', 'choose', 'prison', 'rights'),
  C('technology', 'computer', 'modern', 'machine', 'phone'),
  C('tourism', 'tourist', 'travel', 'visit', 'country'),
  C('recycling', 'plastic', 'waste', 'bin', 'again'),
  C('unemployment', 'job', 'work', 'without', 'people'),
  C('education', 'school', 'learn', 'study', 'teacher'),
  C('government', 'president', 'country', 'law', 'politics'),
  C('election', 'vote', 'president', 'choose', 'politics'),
  C('shopping', 'buy', 'shop', 'mall', 'money'),
  C('supermarket', 'shop', 'food', 'buy', 'big'),
  C('marathon', 'run', 'race', 'kilometres', 'long'),
  C('football', 'ball', 'goal', 'team', 'Messi'),
  C('chess', 'king', 'game', 'board', 'queen'),
  C('guitar', 'music', 'play', 'strings', 'instrument'),
  C('cinema', 'film', 'movie', 'watch', 'screen'),
  C('camera', 'photo', 'picture', 'take', 'lens'),
  C('clock', 'time', 'hour', 'wall', 'minute'),
  C('calendar', 'date', 'day', 'month', 'year'),
  C('weekend', 'Saturday', 'Sunday', 'rest', 'week'),
  C('summer', 'hot', 'season', 'holiday', 'sun'),
  C('bakery', 'bread', 'cake', 'shop', 'bake'),
  C('farmer', 'farm', 'animals', 'field', 'grow'),
  C('pilot', 'plane', 'fly', 'airport', 'captain'),
  C('police', 'crime', 'officer', 'law', 'thief'),
  C('thief', 'steal', 'police', 'crime', 'money'),
  C('lawyer', 'law', 'court', 'judge', 'client'),
  C('scientist', 'science', 'research', 'laboratory', 'experiment'),
  C('medicine', 'ill', 'doctor', 'pill', 'pharmacy'),
  C('exercise', 'sport', 'gym', 'healthy', 'body'),
  C('sleep', 'bed', 'night', 'tired', 'dream'),
  C('dream', 'sleep', 'night', 'wish', 'future'),
  C('future', 'tomorrow', 'years', 'time', 'past'),
  C('memory', 'remember', 'forget', 'brain', 'past'),
  C('village', 'small', 'town', 'countryside', 'people'),
  C('capital', 'city', 'country', 'Tashkent', 'government'),
  C('plov', 'rice', 'meat', 'Uzbek', 'carrot'),
  C('bazaar', 'market', 'buy', 'sell', 'fruit'),
  C('Samarkand', 'city', 'Registan', 'Uzbekistan', 'old'),
  C('metro', 'underground', 'train', 'station', 'Tashkent'),
  C('social media', 'Instagram', 'Telegram', 'online', 'post'),
  C('online learning', 'internet', 'course', 'computer', 'study'),
  C('video game', 'play', 'computer', 'console', 'fun'),
  C('fast food', 'burger', 'quick', 'unhealthy', 'McDonald'),
  C('vegetarian', 'meat', 'eat', 'vegetables', 'animals'),
  C('robot', 'machine', 'artificial', 'human', 'metal'),
  C('artificial intelligence', 'AI', 'computer', 'robot', 'smart'),
  C('space', 'stars', 'planet', 'rocket', 'moon'),
  C('rainbow', 'colours', 'rain', 'sky', 'sun'),
  C('earthquake', 'ground', 'shake', 'disaster', 'building'),
  C('flood', 'water', 'rain', 'river', 'disaster'),
  C('forest', 'trees', 'wood', 'green', 'animals'),
  C('zoo', 'animals', 'cage', 'lion', 'visit'),
  C('elephant', 'big', 'animal', 'trunk', 'grey'),
  C('cat', 'pet', 'animal', 'meow', 'mouse')
];

export const TABOO_CARDS = RAW.map((c, i) => ({ id: `tb${i + 1}`, ...c }));
export default TABOO_CARDS;
