/**
 * Word Sprint vocabulary bank: Destination B2, 14 units (word, synonym where
 * the source gives one, and the Uzbek translation). Parsed from the teacher's
 * "Destination B2 --- Vocabulary Units" document (English word / phrase -- Synonym
 * -- Uzbek translation -- Uzbek explanation, one table per unit); the Uzbek
 * explanation column is not carried over -- nothing in the game reads it, only
 * `word`/`synonym`/`uz` are ever shown (see services/VocabRaceHub.js). The source
 * document repeated a handful of headwords verbatim across its 14 tables; those
 * duplicates were dropped, keeping the first occurrence of each word per unit.
 */

export const VOCAB_RACE_UNITS_DESTINATION_B2 = [
  { num: 2, title: 'Travel and transport', words: [
    { word: 'voyage', uz: 'sayohat (dengiz/kosmik)' },
    { word: 'journey', synonym: 'trip', uz: 'sayohat, safar' },
    { word: 'trip', synonym: 'journey', uz: 'sayohat, ekskursiya' },
    { word: 'travel', synonym: 'journeying', uz: 'sayohat qilish' },
    { word: 'excursion', synonym: 'outing', uz: 'ekskursiya' },
    { word: 'fare', synonym: 'cost', uz: 'yo\'l haqi' },
    { word: 'ticket', synonym: 'pass', uz: 'chipta' },
    { word: 'fee', synonym: 'charge', uz: 'to\'lov, haq' },
    { word: 'live', synonym: 'reside', uz: 'yashamoq' },
    { word: 'stay', synonym: 'remain', uz: 'turmoq, qolmoq' },
    { word: 'view', synonym: 'scene', uz: 'manzara' },
    { word: 'sight', synonym: 'attraction', uz: 'diqqatga sazovor joy; ko\'rish' },
    { word: 'miss', synonym: 'fail to catch', uz: 'o\'tkazib yubormoq' },
    { word: 'lose', synonym: 'misplace', uz: 'yo\'qotmoq' },
    { word: 'border', synonym: 'frontier', uz: 'chegara' },
    { word: 'edge', synonym: 'margin', uz: 'chekka, qirg\'oq' },
    { word: 'line', synonym: 'boundary', uz: 'chiziq, chegara' },
    { word: 'world', synonym: 'globe', uz: 'dunyo' },
    { word: 'earth', synonym: 'planet', uz: 'yer (sayyora)' },
    { word: 'take', synonym: 'carry', uz: 'olib ketmoq' },
    { word: 'bring', synonym: 'fetch', uz: 'olib kelmoq' },
    { word: 'go', synonym: 'travel', uz: 'bormoq, ketmoq' },
    { word: 'length', synonym: 'extent', uz: 'uzunlik' },
    { word: 'distance', synonym: 'space', uz: 'masofa' },
    { word: 'area', synonym: 'region', uz: 'hudud, mintaqa' },
    { word: 'territory', synonym: 'domain', uz: 'hudud, mulk' },
    { word: 'book', synonym: 'reserve', uz: 'band qilmoq' },
    { word: 'keep', synonym: 'retain', uz: 'saqlamoq, ushlab turmoq' },
    { word: 'guide', synonym: 'escort', uz: 'gid, yo\'lboshchi' },
    { word: 'lead', synonym: 'guide', uz: 'boshqarmoq, yetaklamoq' },
    { word: 'season', uz: 'fasl; mavsum' },
    { word: 'period', synonym: 'era', uz: 'davr, muddat' },
    { word: 'arrive', synonym: 'get to', uz: 'yetib kelmoq' },
    { word: 'reach', synonym: 'arrive at', uz: 'yetmoq, yetib bormoq' },
    { word: 'native', synonym: 'local', uz: 'mahalliy, tug\'ilib o\'sgan' },
    { word: 'home', synonym: 'residence', uz: 'uy, vatan' },
    { word: 'catch up with', synonym: 'reach', uz: 'yetib olmoq (darajaga)' },
    { word: 'check in', synonym: 'register', uz: 'ro\'yxatdan o\'tmoq' },
    { word: 'check out', synonym: 'leave', uz: 'chiqib ketmoq (mehmonxonadan)' },
    { word: 'drop off', synonym: 'alight / doze off', uz: 'tushirib qo\'ymoq; mudramoq' },
    { word: 'get back', synonym: 'return', uz: 'qaytib kelmoq' },
    { word: 'go away', synonym: 'depart', uz: 'ta\'tilga chiqmoq' },
    { word: 'keep up with', synonym: 'stay level with', uz: 'bir xil darajada bormoq' },
    { word: 'make for', synonym: 'head for', uz: 'tomon yo\'l olmoq' },
    { word: 'pick up', synonym: 'collect', uz: 'olib ketmoq (yo\'lda)' },
    { word: 'pull in', synonym: 'stop', uz: 'chetga to\'xtamoq' },
    { word: 'run over', synonym: 'hit', uz: '(mashinada) urib yuborish' },
    { word: 'see off', synonym: 'bid farewell', uz: 'jo\'natib qo\'ymoq' },
    { word: 'set out/off', synonym: 'depart', uz: 'yo\'lga chiqmoq' },
    { word: 'take off', synonym: 'lift off', uz: 'ko\'tarilmoq (samolyot)' },
    { word: 'turn round', synonym: 'turn back', uz: 'orqaga qaytmoq' },
    { word: 'accident', synonym: 'crash', uz: 'avariya, baxtsiz hodisa' },
    { word: 'advance', synonym: 'beforehand', uz: 'oldindan; ilgarilash' },
    { word: 'ahead', synonym: 'forward', uz: 'oldinda, oldinga' },
    { word: 'direction', synonym: 'way', uz: 'yo\'nalish' },
    { word: 'head', uz: 'bosh; tomon yo\'l olmoq' },
    { word: 'holiday', synonym: 'vacation', uz: 'ta\'til, bayram' },
    { word: 'left', uz: 'chap (tomon)' },
    { word: 'route', synonym: 'path', uz: 'marshrut' },
    { word: 'sights', synonym: 'attractions', uz: 'diqqatga sazovor joylar' },
    { word: 'sightseeing', synonym: 'touring', uz: 'sayr qilish' },
    { word: 'speed', synonym: 'pace', uz: 'tezlik' },
    { word: 'tour', synonym: 'trip', uz: 'sayohat, tur' },
    { word: 'way', synonym: 'route', uz: 'yo\'l, usul' },
    { word: 'afraid of sth/doing', synonym: 'scared of', uz: 'qo\'rqmoq' },
    { word: 'appear to be', synonym: 'seem to be', uz: 'ko\'rinmoq' },
    { word: 'arrange sth (with sb)', synonym: 'organise', uz: 'kelishmoq, tashkil qilmoq' },
    { word: 'arrive in/at', synonym: 'get to', uz: 'kelmoq, yetib bormoq' },
    { word: 'continue sth/doing', synonym: 'carry on', uz: 'davom ettirmoq' },
    { word: 'differ from', synonym: 'vary from', uz: 'farq qilmoq' },
    { word: 'dream about/of', uz: 'orzu qilmoq; tush ko\'rmoq' },
    { word: 'invite sb to do', synonym: 'ask sb to', uz: 'taklif qilmoq' },
    { word: 'keen to do/on', synonym: 'eager to', uz: 'ishtiyoqli' },
    { word: 'live in/at/on/for', synonym: 'reside', uz: 'yashamoq' },
    { word: 'regret doing/sth', synonym: 'be sorry for', uz: 'afsuslanmoq' },
    { word: 'think of/about', synonym: 'consider', uz: 'o\'ylamoq' },
    { word: 'write about/to/down', synonym: 'note down', uz: 'yozmoq' },
    { word: 'arrange', uz: 'tartibga solmoq / kelishmoq' },
    { word: 'broad', synonym: 'wide', uz: 'keng' },
    { word: 'culture', uz: 'madaniyat' },
    { word: 'differ', synonym: 'vary', uz: 'farq qilmoq' },
    { word: 'direct', uz: 'to\'g\'ridan-to\'g\'ri; yo\'naltirmoq' },
    { word: 'distant', synonym: 'far', uz: 'uzoq (masofada)' },
    { word: 'enter', synonym: 'go in', uz: 'kirmoq' },
    { word: 'inhabit', synonym: 'live in', uz: 'yashamoq (biror joyda)' },
    { word: 'photograph', synonym: 'picture', uz: 'fotosurat' },
    { word: 'recognise', synonym: 'identify', uz: 'tanimoq' },
    { word: 'time', uz: 'vaqt' },
  ] },
  { num: 4, title: 'Hobbies, sport and games', words: [
    { word: 'pitch', synonym: 'field', uz: 'futbol maydoni' },
    { word: 'track', synonym: 'course', uz: 'yugurish yo\'lkasi' },
    { word: 'court', uz: 'kort' },
    { word: 'course', synonym: 'route', uz: 'trassa, maydon' },
    { word: 'ring', uz: 'ring' },
    { word: 'rink', uz: 'katok' },
    { word: 'umpire', synonym: 'referee', uz: 'hakam (tennis, kriket)' },
    { word: 'referee', synonym: 'umpire', uz: 'hakam (futbol, boks)' },
    { word: 'sport', synonym: 'game', uz: 'sport' },
    { word: 'athletics', uz: 'yengil atletika' },
    { word: 'win', synonym: 'succeed', uz: 'g\'alaba qozonmoq' },
    { word: 'beat', synonym: 'defeat', uz: 'yutmoq (raqibni)' },
    { word: 'score', uz: 'hisob to\'plamoq' },
    { word: 'final', uz: 'final (o\'yin)' },
    { word: 'finale', uz: 'final qism' },
    { word: 'end', synonym: 'finish', uz: 'tugash, oxir' },
    { word: 'ending', synonym: 'conclusion', uz: 'yakun' },
    { word: 'interval', synonym: 'break', uz: 'tanaffus' },
    { word: 'half time', uz: 'tanaffus (o\'yin o\'rtasida)' },
    { word: 'play', synonym: 'game', uz: 'o\'yin' },
    { word: 'game', synonym: 'play', uz: 'o\'yin' },
    { word: 'bat', uz: 'bita (kriket/beysbol)' },
    { word: 'stick', uz: 'tayoqcha (xokkey)' },
    { word: 'rod', uz: 'qarmoq tayoqchasi' },
    { word: 'racket', uz: 'raketka' },
    { word: 'draw', synonym: 'tie', uz: 'durrang' },
    { word: 'equal', synonym: 'same', uz: 'teng' },
    { word: 'spectator', synonym: 'onlooker', uz: 'tomoshabin' },
    { word: 'viewer', synonym: 'watcher', uz: 'tomoshabin (TV)' },
    { word: 'amateur', synonym: 'non-professional', uz: 'havaskor' },
    { word: 'professional', synonym: 'expert', uz: 'professional, kasbiy' },
    { word: 'competitor', synonym: 'rival', uz: 'raqib, ishtirokchi' },
    { word: 'opponent', synonym: 'rival', uz: 'raqib' },
    { word: 'bring forward', synonym: 'reschedule earlier', uz: 'muddatini oldinga surmoq' },
    { word: 'carry on', synonym: 'continue', uz: 'davom ettirmoq' },
    { word: 'get round to', synonym: 'finally do', uz: 'qo\'l tekkizmoq' },
    { word: 'get up to', synonym: 'do', uz: 'qilmoq (yomon ish)' },
    { word: 'go in for', synonym: 'enter', uz: 'qatnashmoq, yoqtirmoq' },
    { word: 'go off', synonym: 'stop liking', uz: 'yoqtirmay qo\'ymoq' },
    { word: 'join in', synonym: 'participate', uz: 'qatnashmoq' },
    { word: 'knock out', synonym: 'eliminate', uz: 'mag\'lub etib chiqarmoq' },
    { word: 'look out', synonym: 'be careful', uz: 'ehtiyot bo\'lmoq' },
    { word: 'pull out', synonym: 'withdraw', uz: 'chetlashmoq' },
    { word: 'put off', synonym: 'postpone', uz: 'kechiktirmoq' },
    { word: 'put up with', synonym: 'tolerate', uz: 'chidamoq, toqat qilmoq' },
    { word: 'take to', synonym: 'start liking', uz: 'odat qilib olmoq' },
    { word: 'take up', synonym: 'start', uz: 'shug\'ullana boshlamoq' },
    { word: 'best', uz: 'eng yaxshi' },
    { word: 'chance', synonym: 'opportunity', uz: 'imkoniyat' },
    { word: 'go', synonym: 'turn', uz: 'navbat' },
    { word: 'height', uz: 'balandlik' },
    { word: 'mad', synonym: 'crazy', uz: 'aqldan ozgan; ishqibozi' },
    { word: 'pleasure', synonym: 'enjoyment', uz: 'zavq, rohat' },
    { word: 'popular', synonym: 'liked', uz: 'mashhur, sevimli' },
    { word: 'side', synonym: 'team', uz: 'tomon, jamoa' },
    { word: 'talent', synonym: 'skill', uz: 'iqtidor' },
    { word: 'time', uz: 'vaqt' },
    { word: 'turn', uz: 'navbat' },
    { word: 'compete against/with sb', synonym: 'contend', uz: 'musobaqalashmoq' },
    { word: 'concentrate on', synonym: 'focus on', uz: 'diqqatni jamlamoq' },
    { word: 'difficult to do', synonym: 'hard to do', uz: 'qiyin' },
    { word: 'fond of', synonym: 'like', uz: 'yoqtirmoq' },
    { word: 'free to do', synonym: 'at liberty to', uz: 'erkin' },
    { word: 'interested in', synonym: 'keen on', uz: 'qiziqmoq' },
    { word: 'involve', synonym: 'include', uz: 'o\'z ichiga olmoq' },
    { word: 'listen to', uz: 'tinglamoq' },
    { word: 'love', synonym: 'adore', uz: 'sevmoq, yoqtirmoq' },
    { word: 'mean', synonym: 'signify', uz: 'anglatmoq' },
    { word: 'prefer', synonym: 'like better', uz: 'afzal ko\'rmoq' },
    { word: 'stop', synonym: 'cease', uz: 'to\'xtatmoq' },
    { word: 'sure/certain', synonym: 'confident', uz: 'ishonchli' },
    { word: 'allow', synonym: 'permit', uz: 'ruxsat bermoq' },
    { word: 'associate', synonym: 'connect', uz: 'bog\'lamoq' },
    { word: 'compete', synonym: 'contend', uz: 'musobaqalashmoq' },
    { word: 'enjoy', synonym: 'like', uz: 'zavqlanmoq' },
    { word: 'equip', synonym: 'furnish', uz: 'jihozlamoq' },
    { word: 'fortune', synonym: 'luck', uz: 'baxt, omad' },
    { word: 'interest', uz: 'qiziqish' },
    { word: 'know', uz: 'bilmoq' },
    { word: 'lose', uz: 'yutqazmoq' },
    { word: 'maintain', synonym: 'keep up', uz: 'saqlab turmoq' },
    { word: 'medal', synonym: 'award', uz: 'medal' },
    { word: 'oppose', synonym: 'resist', uz: 'qarshi chiqmoq' },
    { word: 'practice', uz: 'amaliyot, mashq' },
    { word: 'train', synonym: 'coach', uz: 'mashq qildirmoq' },
  ] },
  { num: 6, title: 'Science and technology', words: [
    { word: 'artificial', synonym: 'man-made', uz: 'sun\'iy' },
    { word: 'false', synonym: 'untrue', uz: 'yolg\'on, noto\'g\'ri' },
    { word: 'natural', uz: 'tabiiy' },
    { word: 'physical', synonym: 'bodily', uz: 'jismoniy, moddiy' },
    { word: 'true', synonym: 'correct', uz: 'haqiqiy, to\'g\'ri' },
    { word: 'accurate', synonym: 'precise', uz: 'aniq' },
    { word: 'method', synonym: 'way', uz: 'usul' },
    { word: 'way', synonym: 'method', uz: 'yo\'l, usul' },
    { word: 'engine', synonym: 'motor', uz: 'dvigatel' },
    { word: 'machine', synonym: 'device', uz: 'mashina, qurilma' },
    { word: 'motor', synonym: 'engine', uz: 'motor' },
    { word: 'aim', synonym: 'goal', uz: 'maqsad' },
    { word: 'cause', synonym: 'reason', uz: 'sabab' },
    { word: 'reason', synonym: 'cause', uz: 'sabab, asos' },
    { word: 'estimate', synonym: 'calculate roughly', uz: 'taxminan hisoblamoq' },
    { word: 'calculate', synonym: 'compute', uz: 'hisoblamoq' },
    { word: 'electric', uz: 'elektr (bilan ishlaydigan)' },
    { word: 'electronic', uz: 'elektron' },
    { word: 'invent', synonym: 'create', uz: 'ixtiro qilmoq' },
    { word: 'discover', synonym: 'find', uz: 'kashf etmoq' },
    { word: 'research', synonym: 'study', uz: 'tadqiqot' },
    { word: 'experiment', synonym: 'test', uz: 'tajriba' },
    { word: 'progress', synonym: 'advancement', uz: 'taraqqiyot' },
    { word: 'development', synonym: 'growth', uz: 'rivojlanish' },
    { word: 'modern', synonym: 'contemporary', uz: 'zamonaviy' },
    { word: 'new', synonym: 'recent', uz: 'yangi' },
    { word: 'industry', synonym: 'manufacturing', uz: 'sanoat' },
    { word: 'factory', synonym: 'plant', uz: 'zavod, fabrika' },
    { word: 'award', synonym: 'prize', uz: 'mukofot' },
    { word: 'reward', synonym: 'prize', uz: 'mukofot, taqdirlash' },
    { word: 'take place', synonym: 'happen', uz: 'sodir bo\'lmoq' },
    { word: 'occur', synonym: 'happen', uz: 'yuz bermoq' },
    { word: 'break down', synonym: 'stop working', uz: 'ishlamay qolmoq' },
    { word: 'carry out', synonym: 'perform', uz: 'bajarmoq, amalga oshirmoq' },
    { word: 'come off', synonym: 'succeed', uz: 'muvaffaqiyatli chiqmoq' },
    { word: 'come on', synonym: 'develop', uz: 'rivojlanmoq' },
    { word: 'come up with', synonym: 'think of', uz: 'g\'oya topmoq' },
    { word: 'cut off', synonym: 'disconnect', uz: 'uzib qo\'ymoq' },
    { word: 'find out', synonym: 'discover', uz: 'bilib olmoq' },
    { word: 'give off', synonym: 'emit', uz: 'chiqarmoq (issiqlik, hid)' },
    { word: 'narrow down', synonym: 'reduce', uz: 'qisqartirmoq' },
    { word: 'plug in', synonym: 'connect', uz: 'ulamoq (elektrga)' },
    { word: 'put through', synonym: 'connect', uz: 'ulab bermoq (telefon)' },
    { word: 'turn into', synonym: 'become', uz: 'aylanmoq' },
    { word: 'turn off', synonym: 'switch off', uz: 'o\'chirmoq' },
    { word: 'work out', synonym: 'solve', uz: 'yechim topmoq' },
    { word: 'attempt', synonym: 'try', uz: 'urinish' },
    { word: 'average', synonym: 'mean', uz: 'o\'rtacha' },
    { word: 'beginning', synonym: 'start', uz: 'boshlanish' },
    { word: 'bottom', synonym: 'base', uz: 'tag, pastki qism' },
    { word: 'conclusion', synonym: 'outcome', uz: 'xulosa' },
    { word: 'fact', synonym: 'truth', uz: 'fakt, haqiqat' },
    { word: 'introduction', synonym: 'launch', uz: 'joriy etish' },
    { word: 'phone call', synonym: 'call', uz: 'telefon qo\'ng\'irog\'i' },
    { word: 'photo(graph)', synonym: 'picture', uz: 'fotosurat' },
    { word: 'cause sth (to do)', synonym: 'make', uz: 'sabab bo\'lmoq' },
    { word: 'consider', synonym: 'think about', uz: 'ko\'rib chiqmoq' },
    { word: 'discuss', synonym: 'talk about', uz: 'muhokama qilmoq' },
    { word: 'explain', synonym: 'clarify', uz: 'tushuntirmoq' },
    { word: 'intend', synonym: 'plan', uz: 'niyat qilmoq' },
    { word: 'know', synonym: 'be aware of', uz: 'bilmoq' },
    { word: 'look', uz: 'qaramoq' },
    { word: 'manage to do', synonym: 'succeed in', uz: 'uddalamoq' },
    { word: 'plan', synonym: 'intend', uz: 'rejalashtirmoq' },
    { word: 'possible', synonym: 'feasible', uz: 'mumkin' },
    { word: 'result', synonym: 'consequence', uz: 'natija' },
    { word: 'wonder', synonym: 'ask oneself', uz: 'hayron bo\'lmoq, qiziqmoq' },
    { word: 'appear', synonym: 'seem', uz: 'ko\'rinmoq' },
    { word: 'build', synonym: 'construct', uz: 'qurmoq' },
    { word: 'important', synonym: 'significant', uz: 'muhim' },
    { word: 'introduce', synonym: 'present', uz: 'joriy qilmoq, tanishtirmoq' },
    { word: 'observe', synonym: 'watch', uz: 'kuzatmoq' },
    { word: 'psychology', uz: 'psixologiya' },
    { word: 'revolution', synonym: 'uprising', uz: 'inqilob' },
    { word: 'science', uz: 'fan' },
    { word: 'technology', uz: 'texnologiya' },
    { word: 'wood', synonym: 'timber', uz: 'yog\'och' },
  ] },
  { num: 8, title: 'The media', words: [
    { word: 'deny', synonym: 'refuse to admit', uz: 'rad etmoq, inkor qilmoq' },
    { word: 'refuse', synonym: 'decline', uz: 'rad etmoq' },
    { word: 'agree', synonym: 'accept', uz: 'rozi bo\'lmoq' },
    { word: 'accept', synonym: 'agree', uz: 'qabul qilmoq' },
    { word: 'headline', synonym: 'heading', uz: 'sarlavha (gazeta)' },
    { word: 'heading', synonym: 'title', uz: 'sarlavha' },
    { word: 'feature', synonym: 'article', uz: 'maqola, ocherk' },
    { word: 'article', synonym: 'feature', uz: 'maqola' },
    { word: 'talk show', uz: 'tok-shou' },
    { word: 'quiz show', uz: 'viktorina dasturi' },
    { word: 'game show', uz: 'o\'yin dasturi' },
    { word: 'announcer', synonym: 'presenter', uz: 'diktor' },
    { word: 'commentator', synonym: 'reporter', uz: 'sharhlovchi' },
    { word: 'tabloid', uz: 'tabloid gazeta' },
    { word: 'broadsheet', uz: 'jiddiy gazeta' },
    { word: 'journalist', synonym: 'reporter', uz: 'jurnalist' },
    { word: 'columnist', synonym: 'writer', uz: 'muallif (doimiy ustun)' },
    { word: 'press', synonym: 'media', uz: 'matbuot' },
    { word: 'media', synonym: 'press', uz: 'ommaviy axborot vositalari' },
    { word: 'programme', synonym: 'show', uz: 'dastur' },
    { word: 'program', synonym: 'show', uz: 'dastur' },
    { word: 'channel', synonym: 'station', uz: 'kanal' },
    { word: 'broadcast', synonym: 'transmit', uz: 'efirga uzatmoq' },
    { word: 'bulletin', synonym: 'report', uz: 'axborot, byulleten' },
    { word: 'newsflash', synonym: 'bulletin', uz: 'shoshilinch xabar' },
    { word: 'bring up', synonym: 'raise', uz: 'mavzuni ko\'tarmoq' },
    { word: 'come on', synonym: 'start (broadcast)', uz: 'efirga chiqmoq' },
    { word: 'come out', synonym: 'be published', uz: 'nashr etilmoq' },
    { word: 'fill in', synonym: 'complete', uz: 'to\'ldirmoq' },
    { word: 'flick through', synonym: 'skim', uz: 'varaqlab chiqmoq' },
    { word: 'go into', synonym: 'examine', uz: 'batafsil ko\'rib chiqmoq' },
    { word: 'hand out', synonym: 'distribute', uz: 'tarqatmoq' },
    { word: 'look up', synonym: 'search for', uz: 'qidirmoq (kitobda)' },
    { word: 'make out', synonym: 'pretend / discern', uz: 'qiynalib tushunmoq' },
    { word: 'make up', synonym: 'invent', uz: 'to\'qib chiqarmoq' },
    { word: 'put forward', synonym: 'suggest', uz: 'taklif qilmoq' },
    { word: 'see through', synonym: 'recognise', uz: 'sirini bilib olmoq' },
    { word: 'stand out', synonym: 'be noticeable', uz: 'ajralib turmoq' },
    { word: 'turn over', synonym: 'flip', uz: 'varaqni ag\'darmoq' },
    { word: 'control', synonym: 'authority', uz: 'nazorat' },
    { word: 'description', synonym: 'account', uz: 'tavsif' },
    { word: 'difference', synonym: 'distinction', uz: 'farq' },
    { word: 'granted', synonym: 'assumed', uz: 'oddiy deb qabul qilmoq' },
    { word: 'influence', synonym: 'effect', uz: 'ta\'sir' },
    { word: 'internet', synonym: 'web', uz: 'internet' },
    { word: 'news', synonym: 'report', uz: 'yangilik' },
    { word: 'place', synonym: 'location', uz: 'joy, o\'rin' },
    { word: 'question', synonym: 'query', uz: 'savol' },
    { word: 'view', synonym: 'opinion', uz: 'fikr, nuqtai nazar' },
    { word: 'watch', synonym: 'observe', uz: 'kuzatmoq' },
    { word: 'according to sb', synonym: 'as sb says', uz: 'birov aytishicha' },
    { word: 'announce', synonym: 'declare', uz: 'e\'lon qilmoq' },
    { word: 'believe', synonym: 'think', uz: 'ishonmoq' },
    { word: 'comment on', synonym: 'remark on', uz: 'sharh bermoq' },
    { word: 'confuse', synonym: 'mix up', uz: 'chalkashtirmoq' },
    { word: 'correspond with', synonym: 'communicate with', uz: 'yozishmoq' },
    { word: 'describe', synonym: 'portray', uz: 'tasvirlamoq' },
    { word: 'hear', uz: 'eshitmoq' },
    { word: 'inform', synonym: 'notify', uz: 'xabar bermoq' },
    { word: 'likely', synonym: 'probable', uz: 'ehtimol' },
    { word: 'persuade', synonym: 'convince', uz: 'ko\'ndirmoq' },
    { word: 'point', synonym: 'purpose', uz: 'ma\'no, maqsad' },
    { word: 'send', synonym: 'dispatch', uz: 'yubormoq' },
    { word: 'surprise', synonym: 'astonishment', uz: 'hayrat, ajablanish' },
    { word: 'tell', synonym: 'inform', uz: 'aytmoq' },
    { word: 'belief', synonym: 'faith', uz: 'ishonch' },
    { word: 'communicate', synonym: 'convey', uz: 'aloqa qilmoq' },
    { word: 'convince', synonym: 'persuade', uz: 'ishontirmoq' },
    { word: 'discuss', synonym: 'talk over', uz: 'muhokama qilmoq' },
    { word: 'edit', synonym: 'revise', uz: 'tahrir qilmoq' },
    { word: 'humour', synonym: 'comedy', uz: 'hazil, kulgi' },
    { word: 'journal', synonym: 'publication', uz: 'jurnal' },
    { word: 'politics', uz: 'siyosat' },
    { word: 'power', synonym: 'strength', uz: 'kuch, hokimiyat' },
    { word: 'ridicule', synonym: 'mockery', uz: 'masxara qilmoq' },
    { word: 'second', uz: 'ikkinchi' },
    { word: 'write', synonym: 'compose', uz: 'yozmoq' },
  ] },
  { num: 10, title: 'People and society', words: [
    { word: 'relationship', synonym: 'bond', uz: 'munosabat, aloqa' },
    { word: 'connection', synonym: 'link', uz: 'aloqa, bog\'lanish' },
    { word: 'blame', synonym: 'fault', uz: 'ayb' },
    { word: 'fault', synonym: 'blame', uz: 'ayb, kamchilik' },
    { word: 'old', synonym: 'aged', uz: 'qari, eski' },
    { word: 'ancient', synonym: 'very old', uz: 'qadimiy' },
    { word: 'crowd', synonym: 'mass', uz: 'olomon' },
    { word: 'audience', synonym: 'spectators', uz: 'tomoshabinlar' },
    { word: 'enjoy', synonym: 'like', uz: 'zavqlanmoq' },
    { word: 'please', synonym: 'satisfy', uz: 'xursand qilmoq' },
    { word: 'support', synonym: 'back', uz: 'qo\'llab-quvvatlamoq' },
    { word: 'assist', synonym: 'help', uz: 'yordam bermoq' },
    { word: 'kind', synonym: 'gentle', uz: 'mehribon' },
    { word: 'polite', synonym: 'courteous', uz: 'xushmuomala' },
    { word: 'sympathetic', synonym: 'understanding', uz: 'hamdard' },
    { word: 'likeable', synonym: 'pleasant', uz: 'yoqimli' },
    { word: 'nervous', synonym: 'anxious', uz: 'asabiy, xavotirli' },
    { word: 'bad-tempered', synonym: 'irritable', uz: 'jahldor' },
    { word: 'sensitive', synonym: 'touchy', uz: 'sezgir, ta\'sirchan' },
    { word: 'sensible', synonym: 'reasonable', uz: 'oqilona, aqlli' },
    { word: 'company', synonym: 'firm / companionship', uz: 'kompaniya; hamrohlik' },
    { word: 'group', synonym: 'team', uz: 'guruh' },
    { word: 'popular', synonym: 'well-liked', uz: 'mashhur, sevimli' },
    { word: 'famous', synonym: 'well-known', uz: 'taniqli, mashhur' },
    { word: 'typical', synonym: 'usual', uz: 'odatiy, xarakterli' },
    { word: 'usual', synonym: 'typical', uz: 'odatiy' },
    { word: 'ordinary', synonym: 'normal', uz: 'oddiy' },
    { word: 'close', synonym: 'near', uz: 'yaqin' },
    { word: 'near', synonym: 'close', uz: 'yaqin' },
    { word: 'unknown', synonym: 'unfamiliar', uz: 'noma\'lum' },
    { word: 'infamous', synonym: 'notorious', uz: 'badnom' },
    { word: 'ask after', synonym: 'enquire about', uz: 'sog\'lig\'ini so\'ramoq' },
    { word: 'bring up', synonym: 'raise', uz: 'tarbiyalamoq' },
    { word: 'fall for', synonym: 'fall in love with', uz: 'oshiq bo\'lib qolmoq' },
    { word: 'fall out (with)', synonym: 'quarrel', uz: 'janjallashib qolmoq' },
    { word: 'get on (with)', synonym: 'get along', uz: 'yaxshi munosabatda bo\'lmoq' },
    { word: 'grow up', synonym: 'mature', uz: 'voyaga yetmoq' },
    { word: 'look down on', synonym: 'despise', uz: 'kamsitmoq' },
    { word: 'look up to', synonym: 'admire', uz: 'hurmat qilmoq' },
    { word: 'make up', synonym: 'reconcile', uz: 'yarashib olmoq' },
    { word: 'pass away', synonym: 'die', uz: 'vafot etmoq' },
    { word: 'pick on', synonym: 'bully', uz: 'ta\'na qilmoq' },
    { word: 'put down', synonym: 'criticise', uz: 'kamsitmoq, tanqid qilmoq' },
    { word: 'settle down', synonym: 'calm down', uz: 'tinchlanmoq' },
    { word: 'stand up for', synonym: 'defend', uz: 'himoya qilmoq' },
    { word: 'take aback', synonym: 'surprise', uz: 'hayratda qoldirmoq' },
    { word: 'approval', synonym: 'consent', uz: 'ma\'qullash' },
    { word: 'argument', synonym: 'dispute', uz: 'bahs, tortishuv' },
    { word: 'care', synonym: 'caution', uz: 'g\'amxo\'rlik, ehtiyot' },
    { word: 'courage', synonym: 'bravery', uz: 'jasorat' },
    { word: 'disguise', synonym: 'camouflage', uz: 'niqob, o\'zgartirish' },
    { word: 'dream', synonym: 'aspiration', uz: 'orzu, tush' },
    { word: 'family', synonym: 'relatives', uz: 'oila' },
    { word: 'favour', synonym: 'kindness', uz: 'yaxshilik' },
    { word: 'friend', synonym: 'companion', uz: 'do\'st' },
    { word: 'love', synonym: 'affection', uz: 'sevgi' },
    { word: 'mood', synonym: 'temper', uz: 'kayfiyat' },
    { word: 'pity', synonym: 'sympathy', uz: 'achinish, rahm' },
    { word: 'promise', synonym: 'pledge', uz: 'va\'da' },
    { word: 'agree', synonym: 'consent', uz: 'rozi bo\'lmoq' },
    { word: 'allow', synonym: 'permit', uz: 'ruxsat bermoq' },
    { word: 'approve', synonym: 'sanction', uz: 'ma\'qullamoq' },
    { word: 'ask', synonym: 'request', uz: 'so\'ramoq' },
    { word: 'attack', synonym: 'assault', uz: 'hujum qilmoq' },
    { word: 'ban', synonym: 'prohibit', uz: 'taqiqlamoq' },
    { word: 'convince', synonym: 'persuade', uz: 'ishontirmoq' },
    { word: 'force', synonym: 'compel', uz: 'majburlamoq' },
    { word: 'independent', synonym: 'self-reliant', uz: 'mustaqil' },
    { word: 'let', synonym: 'allow', uz: 'ruxsat bermoq' },
    { word: 'object', synonym: 'oppose', uz: 'e\'tiroz bildirmoq' },
    { word: 'pretend', synonym: 'fake', uz: 'o\'zini ko\'rsatmoq' },
    { word: 'rely on', synonym: 'depend on', uz: 'tayanmoq, ishonmoq' },
    { word: 'able', synonym: 'capable', uz: 'qodir' },
    { word: 'achieve', synonym: 'accomplish', uz: 'erishmoq' },
    { word: 'argue', synonym: 'dispute', uz: 'bahslashmoq' },
    { word: 'correspond', synonym: 'communicate', uz: 'yozishmoq' },
    { word: 'happy', synonym: 'content', uz: 'baxtli' },
    { word: 'jealous', synonym: 'envious', uz: 'hasadgo\'y' },
    { word: 'marry', synonym: 'wed', uz: 'turmush qurmoq' },
    { word: 'nerve', uz: 'asab' },
    { word: 'obey', synonym: 'comply', uz: 'bo\'ysunmoq' },
    { word: 'person', synonym: 'individual', uz: 'shaxs' },
    { word: 'relate', synonym: 'connect', uz: 'bog\'lamoq' },
    { word: 'willing', synonym: 'ready', uz: 'tayyor, xohishli' },
  ] },
  { num: 12, title: 'The law and crime', words: [
    { word: 'proof', synonym: 'evidence', uz: 'dalil, isbot' },
    { word: 'evidence', synonym: 'proof', uz: 'dalil' },
    { word: 'suspect', synonym: 'accused', uz: 'gumon qilinuvchi' },
    { word: 'arrest', synonym: 'detain', uz: 'hibsga olmoq' },
    { word: 'charge', synonym: 'accuse', uz: 'ayblamoq' },
    { word: 'accused', synonym: 'suspect', uz: 'ayblanuvchi' },
    { word: 'decision', synonym: 'verdict', uz: 'qaror' },
    { word: 'verdict', synonym: 'decision', uz: 'hukm (sud)' },
    { word: 'commit', synonym: 'perpetrate', uz: 'sodir etmoq' },
    { word: 'break', synonym: 'violate', uz: 'buzmoq' },
    { word: 'rule', synonym: 'regulation', uz: 'qoida' },
    { word: 'law', synonym: 'legislation', uz: 'qonun' },
    { word: 'justice', synonym: 'fairness', uz: 'adolat' },
    { word: 'right', synonym: 'entitlement', uz: 'huquq' },
    { word: 'judge', synonym: 'magistrate', uz: 'sudya' },
    { word: 'jury', uz: 'ajlyuri (kengash)' },
    { word: 'prosecute', synonym: 'sue', uz: 'sudga bermoq, ayblov qo\'zg\'atmoq' },
    { word: 'persecute', synonym: 'oppress', uz: 'ta\'qib qilmoq' },
    { word: 'capital punishment', synonym: 'death penalty', uz: 'o\'lim jazosi' },
    { word: 'corporal punishment', synonym: 'physical punishment', uz: 'jismoniy jazo' },
    { word: 'robber', synonym: 'thief', uz: 'qaroqchi, o\'g\'ri' },
    { word: 'burglar', synonym: 'thief', uz: 'uy o\'g\'risi' },
    { word: 'thief', synonym: 'robber', uz: 'o\'g\'ri' },
    { word: 'vandal', synonym: 'hooligan', uz: 'vandal, buzg\'unchi' },
    { word: 'hooligan', synonym: 'vandal', uz: 'xuligan' },
    { word: 'sentence', synonym: 'verdict', uz: 'jazo (sud)' },
    { word: 'imprison', synonym: 'jail', uz: 'qamoqqa olmoq' },
    { word: 'innocent', synonym: 'not guilty', uz: 'aybsiz' },
    { word: 'guilty', synonym: 'culpable', uz: 'aybdor' },
    { word: 'witness', synonym: 'eyewitness', uz: 'guvoh' },
    { word: 'bystander', synonym: 'onlooker', uz: 'tomoshabin (guvoh)' },
    { word: 'lawyer', synonym: 'solicitor', uz: 'advokat, yurist' },
    { word: 'solicitor', synonym: 'lawyer', uz: 'huquqshunos' },
    { word: 'back down', synonym: 'give in', uz: 'talabidan qaytmoq' },
    { word: 'break out', synonym: 'escape', uz: 'qochib chiqmoq' },
    { word: 'bring in', synonym: 'introduce', uz: 'joriy qilmoq' },
    { word: 'chase after', synonym: 'pursue', uz: 'ta\'qib qilmoq' },
    { word: 'come forward', synonym: 'volunteer', uz: 'taklif bilan chiqmoq' },
    { word: 'get away with', synonym: 'escape punishment', uz: 'jazosiz qutulmoq' },
    { word: 'go off', synonym: 'explode', uz: 'portlamoq' },
    { word: 'hand in', synonym: 'submit', uz: 'topshirmoq' },
    { word: 'hold up', synonym: 'rob', uz: 'qurollik talon-taroj qilmoq' },
    { word: 'let off', synonym: 'excuse', uz: 'jazosiz qo\'yib yubormoq' },
    { word: 'look into', synonym: 'investigate', uz: 'tergov qilmoq' },
    { word: 'make off', synonym: 'flee', uz: 'qochib ketmoq' },
    { word: 'take down', synonym: 'note', uz: 'yozib olmoq' },
    { word: 'take in', synonym: 'deceive', uz: 'aldamoq' },
    { word: 'account', synonym: 'explanation', uz: 'hisob' },
    { word: 'advantage', synonym: 'benefit', uz: 'ustunlik' },
    { word: 'blame', synonym: 'responsibility', uz: 'ayb' },
    { word: 'damage', synonym: 'harm', uz: 'zarar' },
    { word: 'fault', synonym: 'flaw', uz: 'ayb, kamchilik' },
    { word: 'intention', synonym: 'aim', uz: 'niyat' },
    { word: 'mistake', synonym: 'error', uz: 'xato' },
    { word: 'necessary', synonym: 'essential', uz: 'zarur' },
    { word: 'order', synonym: 'command', uz: 'buyruq, tartib' },
    { word: 'permission', synonym: 'consent', uz: 'ruxsat' },
    { word: 'purpose', synonym: 'aim', uz: 'maqsad' },
    { word: 'reason', synonym: 'cause', uz: 'sabab' },
    { word: 'solution', synonym: 'answer', uz: 'yechim' },
    { word: 'wrong', synonym: 'incorrect', uz: 'noto\'g\'ri' },
    { word: 'accuse', synonym: 'charge', uz: 'ayblamoq' },
    { word: 'claim', synonym: 'assert', uz: 'da\'vo qilmoq' },
    { word: 'deny', synonym: 'refute', uz: 'inkor qilmoq' },
    { word: 'doubt', synonym: 'question', uz: 'shubha qilmoq' },
    { word: 'forgive', synonym: 'pardon', uz: 'kechirmoq' },
    { word: 'glimpse', synonym: 'glance', uz: 'ko\'rib qolmoq' },
    { word: 'legal', synonym: 'lawful', uz: 'qonuniy' },
    { word: 'make', synonym: 'force', uz: 'majbur qilmoq' },
    { word: 'refuse', synonym: 'decline', uz: 'rad etmoq' },
    { word: 'respect', synonym: 'esteem', uz: 'hurmat qilmoq' },
    { word: 'threaten', synonym: 'intimidate', uz: 'tahdid qilmoq' },
    { word: 'addict', uz: 'qaram (kishi)' },
    { word: 'convict', synonym: 'sentence', uz: 'sudlamoq' },
    { word: 'crime', synonym: 'offence', uz: 'jinoyat' },
    { word: 'evident', synonym: 'obvious', uz: 'ayon, aniq' },
    { word: 'forge', synonym: 'fake', uz: 'soxtalashtirmoq' },
    { word: 'honest', synonym: 'truthful', uz: 'halol, samimiy' },
    { word: 'investigate', synonym: 'examine', uz: 'tergov qilmoq' },
    { word: 'murder', synonym: 'killing', uz: 'qotillik' },
    { word: 'offence', synonym: 'crime', uz: 'jinoyat, huquqbuzarlik' },
    { word: 'prison', synonym: 'jail', uz: 'qamoqxona' },
    { word: 'prove', synonym: 'demonstrate', uz: 'isbotlamoq' },
    { word: 'rob', synonym: 'steal from', uz: 'talon-taroj qilmoq' },
    { word: 'secure', synonym: 'safe', uz: 'xavfsiz' },
    { word: 'theft', synonym: 'robbery', uz: 'o\'g\'rilik' },
  ] },
  { num: 14, title: 'Health and fitness', words: [
    { word: 'prescription', uz: 'retsept (dori)' },
    { word: 'recipe', uz: 'retsept (taom)' },
    { word: 'operation', synonym: 'surgery', uz: 'operatsiya' },
    { word: 'surgery', synonym: 'operation', uz: 'jarrohlik' },
    { word: 'sore', synonym: 'painful', uz: 'og\'riqli' },
    { word: 'hurt', synonym: 'injured', uz: 'jarohatlangan' },
    { word: 'pain', synonym: 'ache', uz: 'og\'riq' },
    { word: 'illness', synonym: 'sickness', uz: 'kasallik' },
    { word: 'disease', synonym: 'illness', uz: 'kasallik (tibbiy)' },
    { word: 'injured', synonym: 'hurt', uz: 'jarohatlangan' },
    { word: 'damaged', synonym: 'broken', uz: 'shikastlangan' },
    { word: 'thin', synonym: 'slim', uz: 'ozg\'in' },
    { word: 'slim', synonym: 'thin', uz: 'nozik, ingichka' },
    { word: 'remedy', synonym: 'cure', uz: 'davo' },
    { word: 'cure', synonym: 'remedy', uz: 'davolamoq' },
    { word: 'therapy', synonym: 'treatment', uz: 'terapiya' },
    { word: 'effect', synonym: 'result', uz: 'ta\'sir, natija' },
    { word: 'result', synonym: 'effect', uz: 'natija' },
    { word: 'healthy', synonym: 'fit', uz: 'sog\'lom' },
    { word: 'fit', synonym: 'healthy', uz: 'jismonan bақувват' },
    { word: 'examine', synonym: 'check', uz: 'tekshirmoq' },
    { word: 'investigate', synonym: 'examine', uz: 'tergov qilmoq' },
    { word: 'infection', uz: 'infeksiya' },
    { word: 'pollution', synonym: 'contamination', uz: 'ifloslanish' },
    { word: 'plaster', synonym: 'bandage', uz: 'gips, leykoplastir' },
    { word: 'bandage', synonym: 'dressing', uz: 'bog\'lam' },
    { word: 'ward', uz: 'palata' },
    { word: 'clinic', synonym: 'hospital', uz: 'poliklinika' },
    { word: 'dose', synonym: 'amount', uz: 'doza' },
    { word: 'fix', synonym: 'dose (informal)', uz: 'miqdor (dori)' },
    { word: 'fever', synonym: 'high temperature', uz: 'isitma' },
    { word: 'rash', uz: 'toshma' },
    { word: 'break out', synonym: 'erupt', uz: 'to\'satdan boshlanmoq' },
    { word: 'bring on', synonym: 'cause', uz: 'sabab bo\'lmoq (kasallikka)' },
    { word: 'come down with', synonym: 'catch', uz: 'kasal bo\'lib qolmoq' },
    { word: 'come round/to', synonym: 'regain consciousness', uz: 'hushiga kelmoq' },
    { word: 'cut down (on)', synonym: 'reduce', uz: 'kamaytirmoq' },
    { word: 'feel up to', synonym: 'feel able to', uz: 'o\'zini yaxshi his qilmoq' },
    { word: 'get over', synonym: 'recover from', uz: 'tuzalmoq' },
    { word: 'give up', synonym: 'quit', uz: 'tashlab qo\'ymoq' },
    { word: 'look after', synonym: 'take care of', uz: 'g\'amxo\'rlik qilmoq' },
    { word: 'pass out', synonym: 'faint', uz: 'hushidan ketmoq' },
    { word: 'pull through', synonym: 'survive', uz: 'sog\'ayib chiqmoq' },
    { word: 'put down', synonym: 'euthanise', uz: 'o\'ldirish (kasal hayvonni)' },
    { word: 'put on', synonym: 'gain', uz: 'vazn olmoq' },
    { word: 'wear off', synonym: 'fade', uz: 'ta\'sirini yo\'qotmoq' },
    { word: 'alternative', synonym: 'alternative option', uz: 'muqobil' },
    { word: 'appointment', synonym: 'meeting', uz: 'uchrashuv (shifokor)' },
    { word: 'bath', uz: 'vanna' },
    { word: 'danger', synonym: 'risk', uz: 'xavf' },
    { word: 'exercise', synonym: 'workout', uz: 'mashq' },
    { word: 'good', synonym: 'beneficial', uz: 'foydali' },
    { word: 'health', synonym: 'wellbeing', uz: 'sog\'liq' },
    { word: 'injection', synonym: 'shot', uz: 'ukol' },
    { word: 'medicine', synonym: 'drug', uz: 'dori' },
    { word: 'shape', synonym: 'condition', uz: 'jismoniy holat' },
    { word: 'spread', synonym: 'expansion', uz: 'tarqalish' },
    { word: 'addicted to sth', synonym: 'hooked on', uz: 'qaram bo\'lmoq' },
    { word: 'attempt to do', synonym: 'try', uz: 'urinmoq' },
    { word: 'benefit from sth', synonym: 'gain from', uz: 'foyda ko\'rmoq' },
    { word: 'complain', synonym: 'grumble', uz: 'shikoyat qilmoq' },
    { word: 'cope with', synonym: 'manage', uz: 'bardosh bermoq, uddalamoq' },
    { word: 'inject', synonym: 'administer', uz: 'ukol qilmoq' },
    { word: 'lead to', synonym: 'result in', uz: 'olib kelmoq' },
    { word: 'likely', synonym: 'probable', uz: 'ehtimol' },
    { word: 'need', synonym: 'require', uz: 'ehtiyoj sezmoq' },
    { word: 'operate', synonym: 'perform surgery', uz: 'operatsiya qilmoq' },
    { word: 'suffer', synonym: 'endure', uz: 'azob chekmoq' },
    { word: 'tired of', synonym: 'fed up with', uz: 'charchagan, zerikkan' },
    { word: 'try', synonym: 'attempt', uz: 'harakat qilmoq' },
    { word: 'worry', synonym: 'be anxious', uz: 'xavotirlanmoq' },
    { word: 'worth', synonym: 'valuable', uz: 'arziydigan' },
    { word: 'allergy', uz: 'allergiya' },
    { word: 'aware', synonym: 'conscious', uz: 'xabardor' },
    { word: 'benefit', synonym: 'advantage', uz: 'foyda' },
    { word: 'comfort', synonym: 'ease', uz: 'qulaylik' },
    { word: 'emphasis', synonym: 'stress', uz: 'urg\'u' },
    { word: 'ill', synonym: 'sick', uz: 'kasal' },
    { word: 'injure', synonym: 'harm', uz: 'jarohatlamoq' },
    { word: 'poison', synonym: 'toxin', uz: 'zahar' },
    { word: 'recover', synonym: 'heal', uz: 'tuzalmoq' },
    { word: 'strong', synonym: 'powerful', uz: 'kuchli' },
    { word: 'treat', synonym: 'cure', uz: 'davolamoq' },
  ] },
  { num: 16, title: 'Food and drink', words: [
    { word: 'chop', synonym: 'cut up', uz: 'maydalab to\'g\'ramoq' },
    { word: 'slice', synonym: 'cut', uz: 'tilimlamoq' },
    { word: 'grate', synonym: 'shred', uz: 'qirg\'ichlamoq' },
    { word: 'bake', synonym: 'cook (oven)', uz: 'pishirmoq (pechda)' },
    { word: 'grill', synonym: 'broil', uz: 'panjarada qovurmoq' },
    { word: 'fry', synonym: 'sauté', uz: 'qovurmoq' },
    { word: 'roast', synonym: 'bake', uz: 'qovurmoq (go\'sht)' },
    { word: 'boil', synonym: 'cook in water', uz: 'qaynatmoq' },
    { word: 'cook', synonym: 'prepare food', uz: 'ovqat pishirmoq' },
    { word: 'cooker', synonym: 'stove', uz: 'plita' },
    { word: 'chef', synonym: 'cook', uz: 'oshpaz' },
    { word: 'oven', uz: 'pech' },
    { word: 'hob', synonym: 'stovetop', uz: 'plitaning yuqori qismi' },
    { word: 'kitchen', uz: 'oshxona' },
    { word: 'cuisine', synonym: 'cooking style', uz: 'oshxona uslubi' },
    { word: 'lunch', synonym: 'midday meal', uz: 'tushlik' },
    { word: 'dinner', synonym: 'evening meal', uz: 'kechki ovqat' },
    { word: 'plate', synonym: 'dish', uz: 'likopcha' },
    { word: 'bowl', synonym: 'dish', uz: 'kosa' },
    { word: 'saucer', uz: 'piyola tagligi' },
    { word: 'dish', synonym: 'plate', uz: 'taom' },
    { word: 'vegetable', synonym: 'veg', uz: 'sabzavot' },
    { word: 'vegetarian', uz: 'vegetarian' },
    { word: 'vegan', uz: 'vegan' },
    { word: 'fast food', uz: 'tez tayyorlanadigan ovqat' },
    { word: 'takeaway', synonym: 'takeout', uz: 'olib ketiladigan ovqat' },
    { word: 'kettle', uz: 'choynak (suv qaynatish uchun)' },
    { word: 'teapot', uz: 'choy dami idishi' },
    { word: 'freezer', uz: 'muzlatgich' },
    { word: 'fridge', synonym: 'refrigerator', uz: 'sovutgich' },
    { word: 'frozen', synonym: 'iced', uz: 'muzlatilgan' },
    { word: 'freezing', synonym: 'very cold', uz: 'juda sovuq, muzlatuvchi' },
    { word: 'mix', synonym: 'combine', uz: 'aralashtirmoq' },
    { word: 'stir', synonym: 'mix', uz: 'aralashtirmoq (qoshiq bilan)' },
    { word: 'whisk', synonym: 'beat', uz: 'chalg\'imoq' },
    { word: 'soft drink', uz: 'alkogolsiz ichimlik' },
    { word: 'fizzy drink', synonym: 'carbonated drink', uz: 'gazlangan ichimlik' },
    { word: 'menu', uz: 'menyu' },
    { word: 'catalogue', synonym: 'list', uz: 'katalog' },
    { word: 'drop in (on)', synonym: 'visit unexpectedly', uz: 'to\'satdan tashrif buyurmoq' },
    { word: 'get on for', synonym: 'approach', uz: 'deyarli yetmoq (vaqt/son)' },
    { word: 'go off', synonym: 'spoil', uz: 'buzilib qolmoq' },
    { word: 'go on', synonym: 'continue', uz: 'davom etmoq' },
    { word: 'go/come round', synonym: 'visit', uz: 'mehmonga bormoq/kelmoq' },
    { word: 'keep on', synonym: 'continue', uz: 'davom ettirmoq' },
    { word: 'leave out', synonym: 'omit', uz: 'qoldirib ketmoq' },
    { word: 'put off', synonym: 'discourage', uz: 'xohishini yo\'qotmoq' },
    { word: 'run into', synonym: 'bump into', uz: 'tasodifan uchrashib qolmoq' },
    { word: 'run out of', synonym: 'use up', uz: 'tugatib qo\'ymoq' },
    { word: 'take to', synonym: 'start liking', uz: 'yoqtirib qolmoq' },
    { word: 'try out', synonym: 'test', uz: 'sinab ko\'rmoq' },
    { word: 'turn out', synonym: 'result', uz: 'oxir-oqibat bo\'lmoq' },
    { word: 'turn up', synonym: 'appear', uz: 'paydo bo\'lib qolmoq' },
    { word: 'drink', synonym: 'beverage', uz: 'ichimlik' },
    { word: 'feed', synonym: 'nourish', uz: 'oziqlantirmoq' },
    { word: 'fill', synonym: 'stuff', uz: 'to\'ldirmoq' },
    { word: 'food', synonym: 'meal', uz: 'oziq-ovqat' },
    { word: 'meal', synonym: 'dish', uz: 'ovqatlanish' },
    { word: 'note', synonym: 'memo', uz: 'yozib qo\'yish' },
    { word: 'occasion', synonym: 'event', uz: 'tadbir, holat' },
    { word: 'recipe', synonym: 'formula', uz: 'retsept' },
    { word: 'table', uz: 'stol' },
    { word: 'wash', synonym: 'clean', uz: 'yuvmoq' },
    { word: 'associate', synonym: 'connect', uz: 'bog\'lamoq' },
    { word: 'careful', synonym: 'cautious', uz: 'ehtiyotkor' },
    { word: 'choose', synonym: 'select', uz: 'tanlamoq' },
    { word: 'compliment', synonym: 'praise', uz: 'maqtamoq' },
    { word: 'full of', synonym: 'filled with', uz: 'to\'la' },
    { word: 'lack', synonym: 'shortage', uz: 'yetishmovchilik' },
    { word: 'offer', synonym: 'propose', uz: 'taklif qilmoq' },
    { word: 'regard', synonym: 'consider', uz: 'hisoblamoq' },
    { word: 'remember', synonym: 'recall', uz: 'eslamoq' },
    { word: 'suggest', synonym: 'propose', uz: 'taklif qilmoq' },
    { word: 'tend to do', synonym: 'be inclined to', uz: 'moyil bo\'lmoq' },
    { word: 'wait', uz: 'kutmoq' },
    { word: 'willing to do', synonym: 'ready to', uz: 'tayyor, xohishli' },
    { word: 'anxious', synonym: 'worried', uz: 'xavotirli' },
    { word: 'appreciate', synonym: 'value', uz: 'qadrlamoq' },
    { word: 'contain', synonym: 'hold', uz: 'o\'z ichiga olmoq' },
    { word: 'create', synonym: 'make', uz: 'yaratmoq' },
    { word: 'disgust', synonym: 'revulsion', uz: 'jirkanish' },
    { word: 'grow', synonym: 'increase', uz: 'o\'smoq' },
    { word: 'origin', synonym: 'source', uz: 'kelib chiqishi' },
    { word: 'prepare', synonym: 'get ready', uz: 'tayyorlamoq' },
    { word: 'safe', synonym: 'secure', uz: 'xavfsiz' },
    { word: 'surprise', synonym: 'astonish', uz: 'hayratlantirmoq' },
    { word: 'sweet', synonym: 'sugary', uz: 'shirin' },
    { word: 'thorough', synonym: 'complete', uz: 'puxta, sinchkov' },
  ] },
  { num: 18, title: 'Education and learning', words: [
    { word: 'take', synonym: 'sit (an exam)', uz: 'topshirmoq (imtihon)' },
    { word: 'pass', synonym: 'succeed', uz: 'o\'tmoq (imtihondan)' },
    { word: 'read', synonym: 'study (BrE)', uz: 'o\'qimoq (universitet fani)' },
    { word: 'study', synonym: 'learn', uz: 'o\'qimoq, o\'rganmoq' },
    { word: 'test', synonym: 'exam', uz: 'test, sinov' },
    { word: 'exam', synonym: 'test', uz: 'imtihon' },
    { word: 'primary', synonym: 'elementary', uz: 'boshlang\'ich' },
    { word: 'secondary', synonym: 'high (school)', uz: 'o\'rta (ta\'lim)' },
    { word: 'high', synonym: 'secondary', uz: 'yuqori (maktab)' },
    { word: 'colleague', synonym: 'co-worker', uz: 'hamkasb' },
    { word: 'classmate', synonym: 'schoolmate', uz: 'sinfdosh' },
    { word: 'prefect', uz: 'nazoratchi o\'quvchi' },
    { word: 'pupil', synonym: 'student', uz: 'o\'quvchi (maktab)' },
    { word: 'student', synonym: 'pupil', uz: 'talaba, o\'quvchi' },
    { word: 'qualifications', synonym: 'credentials', uz: 'malaka (hujjat)' },
    { word: 'qualities', synonym: 'characteristics', uz: 'fazilatlar' },
    { word: 'count', synonym: 'matter', uz: 'ahamiyatli bo\'lmoq' },
    { word: 'measure', synonym: 'assess', uz: 'o\'lchamoq' },
    { word: 'degree', synonym: 'qualification', uz: 'diplom (universitet)' },
    { word: 'certificate', synonym: 'diploma', uz: 'sertifikat' },
    { word: 'results', synonym: 'grades', uz: 'natijalar' },
    { word: 'speak', synonym: 'talk', uz: 'gapirmoq' },
    { word: 'talk', synonym: 'speak', uz: 'suhbatlashmoq' },
    { word: 'lesson', synonym: 'class', uz: 'dars' },
    { word: 'subject', synonym: 'topic', uz: 'fan, mavzu' },
    { word: 'achieve', synonym: 'accomplish', uz: 'erishmoq' },
    { word: 'reach', synonym: 'attain', uz: 'yetmoq' },
    { word: 'task', synonym: 'assignment', uz: 'vazifa' },
    { word: 'effort', synonym: 'endeavour', uz: 'harakat, zahmat' },
    { word: 'know', synonym: 'be aware of', uz: 'bilmoq' },
    { word: 'recognise', synonym: 'identify', uz: 'tanimoq' },
    { word: 'teach', synonym: 'instruct', uz: 'o\'qitmoq' },
    { word: 'learn', synonym: 'acquire knowledge', uz: 'o\'rganmoq' },
    { word: 'catch on', synonym: 'understand', uz: 'tushunib olmoq' },
    { word: 'come (a)round (to)', synonym: 'be persuaded', uz: 'fikridan qaytmoq' },
    { word: 'cross out', synonym: 'delete', uz: 'chizib tashlamoq' },
    { word: 'dawn on', synonym: 'realise', uz: 'anglab yetmoq' },
    { word: 'deal with', synonym: 'handle', uz: 'hal qilmoq, shug\'ullanmoq' },
    { word: 'drop out (of)', synonym: 'quit', uz: 'o\'qishni tashlamoq' },
    { word: 'get at', synonym: 'imply', uz: 'ishora qilmoq' },
    { word: 'get on with', synonym: 'continue', uz: 'davom etmoq' },
    { word: 'give in', synonym: 'surrender', uz: 'taslim bo\'lmoq' },
    { word: 'keep up with', synonym: 'stay level with', uz: 'bir xil darajada bormoq' },
    { word: 'sail through', synonym: 'pass easily', uz: 'osonlik bilan o\'tmoq' },
    { word: 'set out', synonym: 'explain', uz: 'batafsil bayon qilmoq' },
    { word: 'think over', synonym: 'consider', uz: 'o\'ylab ko\'rmoq' },
    { word: 'attention', synonym: 'focus', uz: 'e\'tibor' },
    { word: 'break', synonym: 'pause', uz: 'tanaffus' },
    { word: 'discussion', synonym: 'debate', uz: 'muhokama' },
    { word: 'homework', uz: 'uy vazifasi' },
    { word: 'idea', synonym: 'notion', uz: 'g\'oya, fikr' },
    { word: 'mind', synonym: 'opinion / memory', uz: 'fikr, xotira' },
    { word: 'opinion', synonym: 'view', uz: 'fikr' },
    { word: 'point', synonym: 'purpose', uz: 'ma\'no, nuqta' },
    { word: 'sense', synonym: 'meaning', uz: 'ma\'no, tuyg\'u' },
    { word: 'suggestion', synonym: 'proposal', uz: 'taklif' },
    { word: 'able to do', synonym: 'capable of', uz: 'qodir' },
    { word: 'admire', synonym: 'respect', uz: 'hayratlanmoq, hurmat qilmoq' },
    { word: 'boast', synonym: 'brag', uz: 'maqtanmoq' },
    { word: 'capable of', synonym: 'able to', uz: 'qodir' },
    { word: 'congratulate', synonym: 'praise', uz: 'tabriklamoq' },
    { word: 'fail to do', synonym: 'be unable to', uz: 'uddasidan chiqa olmaslik' },
    { word: 'hope', synonym: 'wish', uz: 'umid qilmoq' },
    { word: 'settle for/on sth', synonym: 'agree to', uz: 'kelishmoq, qanoat qilmoq' },
    { word: 'similar to', synonym: 'alike', uz: 'o\'xshash' },
    { word: 'succeed in', synonym: 'manage', uz: 'muvaffaqiyat qozonmoq' },
    { word: 'suitable for', synonym: 'appropriate for', uz: 'mos, munosib' },
    { word: 'academy', synonym: 'institution', uz: 'akademiya' },
    { word: 'attend', synonym: 'go to', uz: 'qatnashmoq (darsga)' },
    { word: 'behave', synonym: 'act', uz: 'o\'zini tutmoq' },
    { word: 'certify', synonym: 'authenticate', uz: 'tasdiqlamoq' },
    { word: 'educate', synonym: 'teach', uz: 'ta\'lim bermoq' },
    { word: 'fail', synonym: 'not succeed', uz: 'muvaffaqiyatsizlikka uchramoq' },
    { word: 'improve', synonym: 'enhance', uz: 'yaxshilamoq' },
    { word: 'intense', synonym: 'extreme', uz: 'kuchli, jadal' },
    { word: 'literate', synonym: 'educated', uz: 'savodli' },
    { word: 'reason', synonym: 'logic', uz: 'mantiq, sabab' },
    { word: 'revise', synonym: 'review', uz: 'takrorlamoq' },
    { word: 'scholar', synonym: 'academic', uz: 'olim' },
    { word: 'solve', synonym: 'resolve', uz: 'yechmoq' },
    { word: 'think', synonym: 'consider', uz: 'o\'ylamoq' },
    { word: 'understand', synonym: 'comprehend', uz: 'tushunmoq' },
  ] },
  { num: 20, title: 'Weather and the environment', words: [
    { word: 'urban', synonym: 'city', uz: 'shaharga oid' },
    { word: 'suburban', uz: 'shahar chekkasiga oid' },
    { word: 'rural', synonym: 'countryside', uz: 'qishloqqa oid' },
    { word: 'smog', uz: 'smog (tutun-tuman)' },
    { word: 'fog', synonym: 'mist', uz: 'tuman' },
    { word: 'smoke', uz: 'tutun' },
    { word: 'mist', synonym: 'fog', uz: 'yengil tuman' },
    { word: 'weather', synonym: 'climate', uz: 'ob-havo' },
    { word: 'climate', synonym: 'weather', uz: 'iqlim' },
    { word: 'forecast', synonym: 'prediction', uz: 'bashorat (ob-havo)' },
    { word: 'prediction', synonym: 'forecast', uz: 'bashorat' },
    { word: 'waste', synonym: 'rubbish', uz: 'chiqindi' },
    { word: 'litter', synonym: 'rubbish', uz: 'axlat (ko\'chadagi)' },
    { word: 'rubbish', synonym: 'waste', uz: 'axlat, chiqindi' },
    { word: 'clean', uz: 'toza' },
    { word: 'clear', synonym: 'bright', uz: 'ochiq, tiniq (havo)' },
    { word: 'pour', synonym: 'rain heavily', uz: 'kuchli yomg\'ir yog\'moq' },
    { word: 'drizzle', synonym: 'light rain', uz: 'mayda yomg\'ir' },
    { word: 'flood', uz: 'suv toshqini' },
    { word: 'environment', synonym: 'surroundings', uz: 'atrof-muhit' },
    { word: 'surroundings', synonym: 'environment', uz: 'atrof, muhit' },
    { word: 'wind', synonym: 'breeze', uz: 'shamol' },
    { word: 'air', synonym: 'atmosphere', uz: 'havo' },
    { word: 'reservoir', uz: 'suv ombori' },
    { word: 'lake', uz: 'ko\'l' },
    { word: 'puddle', uz: 'loycha (yomg\'irdan keyin)' },
    { word: 'pond', uz: 'hovuz' },
    { word: 'thunder', uz: 'momaqaldiroq' },
    { word: 'lightning', uz: 'chaqmoq' },
    { word: 'global', synonym: 'worldwide', uz: 'global, umumjahon' },
    { word: 'worldwide', synonym: 'global', uz: 'butun dunyo bo\'ylab' },
    { word: 'plain', synonym: 'field', uz: 'tekislik' },
    { word: 'land', synonym: 'ground', uz: 'yer, quruqlik' },
    { word: 'field', synonym: 'plain', uz: 'dala, maydon' },
    { word: 'desert', uz: 'cho\'l' },
    { word: 'extinct', uz: 'qirilib ketgan' },
    { word: 'endangered', synonym: 'threatened', uz: 'yo\'qolib ketish xavfi ostidagi' },
    { word: 'recycle', synonym: 'reprocess', uz: 'qayta ishlamoq' },
    { word: 'reuse', synonym: 'recycle', uz: 'qayta ishlatmoq' },
    { word: 'call for', synonym: 'require', uz: 'talab qilmoq' },
    { word: 'call off', synonym: 'cancel', uz: 'bekor qilmoq' },
    { word: 'clear up', synonym: 'brighten', uz: 'ochilib ketmoq (havo)' },
    { word: 'cut off', synonym: 'isolate', uz: 'ajratib qo\'ymoq' },
    { word: 'die down', synonym: 'subside', uz: 'pasaymoq, tinchimoq' },
    { word: 'do up', synonym: 'renovate', uz: 'ta\'mirlamoq' },
    { word: 'face up to', synonym: 'accept', uz: 'yuzlashmoq, tan olmoq' },
    { word: 'get (sb) down', synonym: 'depress', uz: 'tushkunlikka solmoq' },
    { word: 'put down to', synonym: 'attribute to', uz: 'sababini bog\'lamoq' },
    { word: 'put out', synonym: 'extinguish', uz: 'o\'chirmoq (olov)' },
    { word: 'set in', synonym: 'begin', uz: 'boshlanmoq (uzoq davom etadigan)' },
    { word: 'stand for', synonym: 'represent', uz: 'anglatmoq' },
    { word: 'tear down', synonym: 'demolish', uz: 'buzib tashlamoq' },
    { word: 'throw away', synonym: 'discard', uz: 'tashlab yubormoq' },
    { word: 'control', synonym: 'authority', uz: 'nazorat' },
    { word: 'effect', synonym: 'impact', uz: 'ta\'sir' },
    { word: 'end', synonym: 'conclusion', uz: 'oxir, yakun' },
    { word: 'floor', synonym: 'ground', uz: 'pol, qavat' },
    { word: 'fuss', synonym: 'commotion', uz: 'g\'alva, tashvish' },
    { word: 'long', synonym: 'extended', uz: 'uzoq' },
    { word: 'look', synonym: 'glance', uz: 'qarash' },
    { word: 'mess', synonym: 'disorder', uz: 'tartibsizlik' },
    { word: 'responsibility', synonym: 'duty', uz: 'mas\'uliyat' },
    { word: 'shower', synonym: 'rain', uz: 'dush; yomg\'ir' },
    { word: 'sight', synonym: 'view', uz: 'ko\'rinish' },
    { word: 'world', synonym: 'globe', uz: 'dunyo' },
    { word: 'aware of sth', synonym: 'conscious of', uz: 'xabardor' },
    { word: 'covered in/with sth', synonym: 'coated', uz: 'qoplangan' },
    { word: 'disappointed with/by sth', synonym: 'let down', uz: 'hafsalasi pir bo\'lgan' },
    { word: 'except (for)', synonym: 'apart from', uz: 'bundan tashqari' },
    { word: 'expect', synonym: 'anticipate', uz: 'kutmoq' },
    { word: 'familiar with', synonym: 'acquainted with', uz: 'tanish' },
    { word: 'famous for', synonym: 'known for', uz: 'mashhur' },
    { word: 'glance at', synonym: 'look briefly', uz: 'qisqa qaramoq' },
    { word: 'hard to do', synonym: 'difficult', uz: 'qiyin' },
    { word: 'prevent', synonym: 'stop', uz: 'oldini olmoq' },
    { word: 'short of', synonym: 'lacking', uz: 'yetishmovchi' },
    { word: 'warn', synonym: 'caution', uz: 'ogohlantirmoq' },
    { word: 'accurate', synonym: 'precise', uz: 'aniq' },
    { word: 'danger', synonym: 'risk', uz: 'xavf' },
    { word: 'develop', synonym: 'grow', uz: 'rivojlanmoq' },
    { word: 'extreme', synonym: 'severe', uz: 'o\'ta, keskin' },
    { word: 'freeze', uz: 'muzlamoq' },
    { word: 'globe', synonym: 'world', uz: 'globus, yer shari' },
    { word: 'great', synonym: 'large', uz: 'katta, ajoyib' },
    { word: 'harm', synonym: 'damage', uz: 'zarar' },
    { word: 'likely', synonym: 'probable', uz: 'ehtimol' },
    { word: 'low', uz: 'past' },
    { word: 'nature', uz: 'tabiat' },
    { word: 'neighbour', uz: 'qo\'shni' },
    { word: 'pollute', synonym: 'contaminate', uz: 'ifloslantirmoq' },
    { word: 'reside', synonym: 'live', uz: 'istiqomat qilmoq' },
    { word: 'sun', uz: 'quyosh' },
  ] },
  { num: 22, title: 'Money and shopping', words: [
    { word: 'economic', synonym: 'financial', uz: 'iqtisodiy' },
    { word: 'economical', synonym: 'cost-effective', uz: 'tejamkor' },
    { word: 'receipt', uz: 'chek' },
    { word: 'bill', synonym: 'invoice', uz: 'hisob-faktura' },
    { word: 'make', synonym: 'brand', uz: 'ishlab chiqaruvchi (marka)' },
    { word: 'brand', synonym: 'make', uz: 'brend' },
    { word: 'bargain', synonym: 'good deal', uz: 'arzon narx, chegirma' },
    { word: 'sale', synonym: 'discount', uz: 'chegirma savdosi' },
    { word: 'discount', synonym: 'reduction', uz: 'chegirma' },
    { word: 'offer', synonym: 'deal', uz: 'taklif, aksiya' },
    { word: 'price', synonym: 'cost', uz: 'narx' },
    { word: 'cost', synonym: 'price', uz: 'qiymat, narx' },
    { word: 'change', synonym: 'coins', uz: 'qaytim' },
    { word: 'cash', synonym: 'money', uz: 'naqd pul' },
    { word: 'wealth', synonym: 'riches', uz: 'boylik' },
    { word: 'fortune', synonym: 'wealth', uz: 'boylik, katta pul' },
    { word: 'till', synonym: 'checkout', uz: 'kassa' },
    { word: 'checkout', synonym: 'till', uz: 'kassa (chiqish joyi)' },
    { word: 'products', synonym: 'goods', uz: 'mahsulotlar' },
    { word: 'goods', synonym: 'products', uz: 'tovarlar' },
    { word: 'refund', synonym: 'repayment', uz: 'pulni qaytarish' },
    { word: 'exchange', synonym: 'swap', uz: 'almashtirish' },
    { word: 'fake', synonym: 'counterfeit', uz: 'soxta' },
    { word: 'plastic', synonym: 'card', uz: 'plastik karta' },
    { word: 'bank on', synonym: 'rely on', uz: 'umid bog\'lamoq' },
    { word: 'come across', synonym: 'find', uz: 'tasodifan topmoq/uchratmoq' },
    { word: 'come by', synonym: 'obtain', uz: 'topish qiyin narsani qo\'lga kiritmoq' },
    { word: 'come into', synonym: 'inherit', uz: 'meros olmoq' },
    { word: 'do without', synonym: 'manage without', uz: '-siz yashamoq' },
    { word: 'get by', synonym: 'manage', uz: 'kun ko\'rmoq' },
    { word: 'get through', synonym: 'use up', uz: 'sarflab bo\'lmoq' },
    { word: 'give away', synonym: 'donate', uz: 'bepul bermoq' },
    { word: 'live on', synonym: 'subsist on', uz: '-ga qarab kun ko\'rmoq' },
    { word: 'look round', synonym: 'browse', uz: 'ko\'zdan kechirmoq' },
    { word: 'make out', synonym: 'fill in', uz: 'to\'ldirib yozmoq' },
    { word: 'make up for', synonym: 'compensate for', uz: 'o\'rnini qoplamoq' },
    { word: 'put by', synonym: 'save', uz: 'pul yig\'ib qo\'ymoq' },
    { word: 'save up (for)', synonym: 'put aside', uz: 'pul jamg\'armoq' },
    { word: 'amount', synonym: 'quantity', uz: 'miqdor' },
    { word: 'charge', synonym: 'fee', uz: 'to\'lov' },
    { word: 'debt', synonym: 'liability', uz: 'qarz' },
    { word: 'demand', synonym: 'request', uz: 'talab' },
    { word: 'enough', synonym: 'sufficient', uz: 'yetarli' },
    { word: 'expense', synonym: 'cost', uz: 'xarajat' },
    { word: 'increase', synonym: 'rise', uz: 'oshish' },
    { word: 'least', synonym: 'minimum', uz: 'eng kami' },
    { word: 'money', synonym: 'cash', uz: 'pul' },
    { word: 'notice', synonym: 'warning', uz: 'ogohlantirish, e\'lon' },
    { word: 'profit', synonym: 'gain', uz: 'foyda' },
    { word: 'save', synonym: 'put aside', uz: 'tejamoq' },
    { word: 'shopping', synonym: 'purchasing', uz: 'xarid qilish' },
    { word: 'afford', synonym: 'manage financially', uz: 'qurbi yetmoq' },
    { word: 'argue', synonym: 'dispute', uz: 'bahslashmoq' },
    { word: 'beg', synonym: 'plead', uz: 'yolvormoq' },
    { word: 'belong to', synonym: 'be owned by', uz: 'tegishli bo\'lmoq' },
    { word: 'borrow', synonym: 'take a loan', uz: 'qarz olmoq' },
    { word: 'forget', uz: 'unutmoq' },
    { word: 'lend', synonym: 'loan', uz: 'qarz bermoq' },
    { word: 'pay', synonym: 'settle', uz: 'to\'lamoq' },
    { word: 'spend', synonym: 'expend', uz: 'sarflamoq' },
    { word: 'accept', synonym: 'agree to', uz: 'qabul qilmoq' },
    { word: 'assist', synonym: 'help', uz: 'yordam bermoq' },
    { word: 'day', uz: 'kun' },
    { word: 'economy', uz: 'iqtisodiyot' },
    { word: 'end', synonym: 'finish', uz: 'tugash' },
    { word: 'finance', synonym: 'funding', uz: 'moliya' },
    { word: 'invest', synonym: 'put money into', uz: 'sarmoya kiritmoq' },
    { word: 'luxury', synonym: 'extravagance', uz: 'hashamat' },
    { word: 'poor', synonym: 'needy', uz: 'kambag\'al' },
    { word: 'real', synonym: 'genuine', uz: 'haqiqiy' },
    { word: 'value', synonym: 'worth', uz: 'qiymat' },
  ] },
  { num: 24, title: 'Entertainment', words: [
    { word: 'enjoy', synonym: 'like', uz: 'zavqlanmoq' },
    { word: 'entertain', synonym: 'amuse', uz: 'ko\'ngil ochmoq' },
    { word: 'play', synonym: 'perform', uz: 'o\'ynamoq, ijro etmoq' },
    { word: 'act', synonym: 'perform', uz: 'rol o\'ynamoq' },
    { word: 'star', synonym: 'feature', uz: 'bosh rolni o\'ynamoq' },
    { word: 'audition', synonym: 'tryout', uz: 'tanlov (aktyorlik)' },
    { word: 'rehearsal', synonym: 'practice', uz: 'repetitsiya' },
    { word: 'rehearse', synonym: 'practise', uz: 'repetitsiya qilmoq' },
    { word: 'practise', synonym: 'rehearse', uz: 'mashq qilmoq' },
    { word: 'scene', uz: 'sahna (epizod)' },
    { word: 'scenery', synonym: 'setting', uz: 'dekoratsiya' },
    { word: 'stage', synonym: 'platform', uz: 'sahna' },
    { word: 'band', synonym: 'group', uz: 'guruh (musiqa)' },
    { word: 'orchestra', uz: 'orkestr' },
    { word: 'group', synonym: 'band', uz: 'guruh' },
    { word: 'review', synonym: 'critique', uz: 'taqriz, sharh' },
    { word: 'criticism', synonym: 'critique', uz: 'tanqid' },
    { word: 'ticket', synonym: 'pass', uz: 'chipta' },
    { word: 'fee', synonym: 'charge', uz: 'to\'lov, haq' },
    { word: 'novel', uz: 'roman' },
    { word: 'fiction', uz: 'badiiy adabiyot' },
    { word: 'comic', synonym: 'comedian', uz: 'komik' },
    { word: 'cartoon', synonym: 'animation', uz: 'multfilm' },
    { word: 'comedian', synonym: 'comic', uz: 'komediyachi' },
    { word: 'watch', synonym: 'view', uz: 'tomosha qilmoq' },
    { word: 'see', synonym: 'watch', uz: 'ko\'rmoq' },
    { word: 'look', synonym: 'view', uz: 'qaramoq' },
    { word: 'listen', uz: 'tinglamoq' },
    { word: 'hear', synonym: 'listen', uz: 'eshitmoq' },
    { word: 'come (a)round', synonym: 'recur', uz: 'qayta takrorlanmoq' },
    { word: 'count on', synonym: 'rely on', uz: 'ishonmoq, tayanmoq' },
    { word: 'drop off', synonym: 'fall asleep', uz: 'uxlab qolmoq' },
    { word: 'drown out', synonym: 'overpower (sound)', uz: 'ovozni bosib ketmoq' },
    { word: 'fall for', synonym: 'be fooled by', uz: 'aldanib qolmoq' },
    { word: 'get along (with)', synonym: 'get on with', uz: 'yaxshi munosabatda bo\'lmoq' },
    { word: 'go down (as)', synonym: 'be remembered as', uz: 'tarixda qolmoq' },
    { word: 'grow on', synonym: 'become more liked', uz: 'asta-sekin yoqib qolmoq' },
    { word: 'let down', synonym: 'disappoint', uz: 'xafa qilmoq' },
    { word: 'name after', synonym: 'call after', uz: 'nomini qo\'ymoq' },
    { word: 'put on', synonym: 'stage', uz: 'namoyish qilmoq' },
    { word: 'show off', synonym: 'boast', uz: 'ko\'z-ko\'z qilmoq' },
    { word: 'take after', synonym: 'resemble', uz: 'o\'xshab ketmoq' },
    { word: 'take off', synonym: 'become popular', uz: 'mashhur bo\'lib ketmoq' },
    { word: 'fun', synonym: 'enjoyment', uz: 'zavq, ko\'ngilochar' },
    { word: 'funny', synonym: 'amusing', uz: 'kulgili' },
    { word: 'home', synonym: 'house', uz: 'uy' },
    { word: 'impression', synonym: 'perception', uz: 'taassurot' },
    { word: 'joke', synonym: 'gag', uz: 'hazil, latifa' },
    { word: 'laugh', synonym: 'chuckle', uz: 'kulgi' },
    { word: 'part', synonym: 'role', uz: 'qism, rol' },
    { word: 'party', synonym: 'celebration', uz: 'ziyofat' },
    { word: 'queue', synonym: 'line', uz: 'navbat' },
    { word: 'show', synonym: 'performance', uz: 'namoyish, ko\'rsatuv' },
    { word: 'silence', synonym: 'quiet', uz: 'sukunat' },
    { word: 'voice', synonym: 'tone', uz: 'ovoz' },
    { word: 'apologise', synonym: 'say sorry', uz: 'uzr so\'ramoq' },
    { word: 'avoid', synonym: 'evade', uz: 'qochmoq, oldini olmoq' },
    { word: 'bound to do', synonym: 'certain to', uz: 'albatta qiladigan' },
    { word: 'deserve', synonym: 'merit', uz: 'loyiq bo\'lmoq' },
    { word: 'happy', synonym: 'pleased', uz: 'xursand' },
    { word: 'instead of', synonym: 'rather than', uz: 'o\'rniga' },
    { word: 'like', synonym: 'enjoy', uz: 'yoqtirmoq' },
    { word: 'promise', synonym: 'pledge', uz: 'va\'da bermoq' },
    { word: 'prove', synonym: 'demonstrate', uz: 'isbotlamoq' },
    { word: 'say', synonym: 'state', uz: 'aytmoq' },
    { word: 'supposed to do', synonym: 'expected to', uz: 'qilishi kerak (kutilgan)' },
    { word: 'talented at', synonym: 'skilled at', uz: 'iste\'dodli' },
    { word: 'amuse', synonym: 'entertain', uz: 'kulgi qilmoq, xursand qilmoq' },
    { word: 'bore', synonym: 'tire', uz: 'zeriktirmoq' },
    { word: 'converse', synonym: 'talk', uz: 'suhbatlashmoq' },
    { word: 'current', synonym: 'present', uz: 'hozirgi' },
    { word: 'excite', synonym: 'thrill', uz: 'hayajonlantirmoq' },
    { word: 'fame', synonym: 'renown', uz: 'shuhrat' },
    { word: 'involve', synonym: 'include', uz: 'jalb qilmoq' },
    { word: 'perform', synonym: 'act', uz: 'ijro etmoq' },
    { word: 'popular', synonym: 'well-liked', uz: 'mashhur' },
    { word: 'suggest', synonym: 'propose', uz: 'taklif qilmoq' },
    { word: 'vary', synonym: 'differ', uz: 'farq qilmoq, o\'zgarmoq' },
  ] },
  { num: 26, title: 'Fashion and design', words: [
    { word: 'put on', synonym: 'wear', uz: 'kiymoq' },
    { word: 'wear', synonym: 'put on', uz: 'kiymoq' },
    { word: 'costume', synonym: 'outfit', uz: 'kostyum (teatr/bayram)' },
    { word: 'suit', synonym: 'outfit', uz: 'kostyum (rasmiy)' },
    { word: 'dye', synonym: 'colour', uz: 'bo\'yamoq (mato/soch)' },
    { word: 'paint', synonym: 'colour', uz: 'bo\'yamoq (rasm)' },
    { word: 'fit', synonym: 'suit', uz: 'mos kelmoq (o\'lcham)' },
    { word: 'match', synonym: 'fit', uz: 'mos kelmoq (rang/uslub)' },
    { word: 'cloth', synonym: 'fabric', uz: 'mato' },
    { word: 'clothing', synonym: 'clothes', uz: 'kiyim-kechak' },
    { word: 'blouse', synonym: 'top', uz: 'bluzka' },
    { word: 'top', synonym: 'blouse', uz: 'ustki kiyim' },
    { word: 'design', synonym: 'create', uz: 'loyihalamoq' },
    { word: 'manufacture', synonym: 'produce', uz: 'ishlab chiqarmoq' },
    { word: 'current', synonym: 'present', uz: 'hozirgi' },
    { word: 'new', synonym: 'recent', uz: 'yangi' },
    { word: 'modern', synonym: 'contemporary', uz: 'zamonaviy' },
    { word: 'look', synonym: 'appearance', uz: 'ko\'rinish' },
    { word: 'appearance', synonym: 'look', uz: 'tashqi ko\'rinish' },
    { word: 'supply', synonym: 'provide', uz: 'ta\'minlamoq' },
    { word: 'produce', synonym: 'manufacture', uz: 'ishlab chiqarmoq' },
    { word: 'glimpse', synonym: 'glance', uz: 'ko\'z tashlab olish' },
    { word: 'glance', synonym: 'glimpse', uz: 'ko\'z yugurtirish' },
    { word: 'average', synonym: 'ordinary', uz: 'o\'rtacha, oddiy' },
    { word: 'everyday', synonym: 'ordinary', uz: 'kundalik, oddiy' },
    { word: 'catch on', synonym: 'become popular', uz: 'mashhur bo\'lib qolmoq' },
    { word: 'do away with', synonym: 'eliminate', uz: 'yo\'q qilmoq' },
    { word: 'draw up', synonym: 'prepare', uz: 'tuzmoq (reja)' },
    { word: 'dress up', synonym: 'get dressed up', uz: 'bezanib kiyinmoq' },
    { word: 'go over', synonym: 'review', uz: 'qayta ko\'rib chiqmoq' },
    { word: 'grow out of', synonym: 'outgrow', uz: 'kichik kelib qolmoq' },
    { word: 'hand down', synonym: 'pass on', uz: 'meros qoldirmoq' },
    { word: 'line up', synonym: 'queue', uz: 'navbatga turmoq' },
    { word: 'pop in(to)', synonym: 'visit briefly', uz: 'tez tashrif buyurmoq' },
    { word: 'show (a)round', synonym: 'give a tour', uz: 'sayr qildirmoq' },
    { word: 'take off', synonym: 'remove', uz: 'yechmoq (kiyim)' },
    { word: 'tear up', synonym: 'rip', uz: 'yirtib tashlamoq' },
    { word: 'try on', synonym: 'fit', uz: 'kiyib ko\'rmoq' },
    { word: 'wear out', synonym: 'become worn', uz: 'eskirib qolmoq' },
    { word: 'art', synonym: 'artwork', uz: 'san\'at' },
    { word: 'clothes', synonym: 'garments', uz: 'kiyim-kechak' },
    { word: 'combination', synonym: 'mix', uz: 'kombinatsiya' },
    { word: 'compliment', synonym: 'praise', uz: 'ta\'rif, maqtov' },
    { word: 'example', synonym: 'instance', uz: 'misol' },
    { word: 'fashion', synonym: 'style', uz: 'moda' },
    { word: 'hair', uz: 'soch' },
    { word: 'make-up', synonym: 'cosmetics', uz: 'makiyaj' },
    { word: 'pattern', synonym: 'design', uz: 'naqsh, andoza' },
    { word: 'style', synonym: 'fashion', uz: 'uslub' },
    { word: 'taste', synonym: 'preference', uz: 'did, ta\'b' },
    { word: 'tendency', synonym: 'inclination', uz: 'moyillik' },
    { word: 'trend', synonym: 'fashion', uz: 'tendensiya, moda' },
    { word: 'advise', synonym: 'recommend', uz: 'maslahat bermoq' },
    { word: 'anxious', synonym: 'worried', uz: 'xavotirli, ishtiyoqli' },
    { word: 'criticise', synonym: 'condemn', uz: 'tanqid qilmoq' },
    { word: 'insist', synonym: 'demand', uz: 'qat\'iy talab qilmoq' },
    { word: 'plenty', synonym: 'a lot', uz: 'ko\'p, yetarlicha' },
    { word: 'prepare', synonym: 'get ready', uz: 'tayyorlamoq' },
    { word: 'proud', synonym: 'pleased', uz: 'g\'ururlangan' },
    { word: 'refer to', synonym: 'mention', uz: 'murojaat qilmoq' },
    { word: 'seem', synonym: 'appear', uz: 'ko\'rinmoq' },
    { word: 'stare at', synonym: 'gaze at', uz: 'tikilib qaramoq' },
    { word: 'use', synonym: 'utilise', uz: 'foydalanmoq' },
    { word: 'useful', synonym: 'helpful', uz: 'foydali' },
    { word: 'advertise', synonym: 'promote', uz: 'reklama qilmoq' },
    { word: 'attract', synonym: 'draw', uz: 'jalb qilmoq' },
    { word: 'beauty', synonym: 'attractiveness', uz: 'go\'zallik' },
    { word: 'decide', synonym: 'determine', uz: 'qaror qilmoq' },
    { word: 'desire', synonym: 'wish', uz: 'xohlamoq, istak' },
    { word: 'enthuse', synonym: 'excite', uz: 'ilhomlantirmoq' },
    { word: 'expect', synonym: 'anticipate', uz: 'kutmoq' },
    { word: 'like', synonym: 'similar', uz: 'o\'xshash' },
    { word: 'similar', synonym: 'alike', uz: 'o\'xshash' },
    { word: 'succeed', synonym: 'achieve', uz: 'muvaffaqiyat qozonmoq' },
  ] },
  { num: 28, title: 'Work and business', words: [
    { word: 'employer', synonym: 'boss', uz: 'ish beruvchi' },
    { word: 'employee', synonym: 'worker', uz: 'xodim' },
    { word: 'staff', synonym: 'personnel', uz: 'xodimlar' },
    { word: 'job', synonym: 'work', uz: 'ish' },
    { word: 'work', synonym: 'job', uz: 'ish, mehnat' },
    { word: 'career', synonym: 'profession', uz: 'kasb, martaba' },
    { word: 'earn', synonym: 'gain', uz: 'ishlab topmoq' },
    { word: 'win', synonym: 'gain', uz: 'yutib olmoq' },
    { word: 'gain', synonym: 'earn', uz: 'qo\'lga kiritmoq' },
    { word: 'raise', synonym: 'increase', uz: 'ko\'tarmoq, oshirmoq' },
    { word: 'rise', synonym: 'increase', uz: 'ko\'tarilish' },
    { word: 'wage(s)', synonym: 'pay', uz: 'ish haqi (soatlik/kunlik)' },
    { word: 'salary', synonym: 'pay', uz: 'oylik maosh' },
    { word: 'pay', synonym: 'salary', uz: 'to\'lov, maosh' },
    { word: 'commute', synonym: 'travel to work', uz: 'ishga qatnamoq' },
    { word: 'deliver', synonym: 'bring', uz: 'yetkazib bermoq' },
    { word: 'retire', synonym: 'stop working', uz: 'nafaqaga chiqmoq' },
    { word: 'resign', synonym: 'quit', uz: 'iste\'foga chiqmoq' },
    { word: 'fire', synonym: 'dismiss', uz: 'ishdan bo\'shatmoq' },
    { word: 'sack', synonym: 'fire', uz: 'ishdan haydamoq' },
    { word: 'make redundant', synonym: 'lay off', uz: 'shtatdan chiqarmoq' },
    { word: 'overtime', uz: 'qo\'shimcha ish vaqti' },
    { word: 'promotion', synonym: 'advancement', uz: 'lavozimni oshirish' },
    { word: 'pension', uz: 'pensiya' },
    { word: 'company', synonym: 'firm', uz: 'kompaniya' },
    { word: 'firm', synonym: 'company', uz: 'firma' },
    { word: 'business', synonym: 'company', uz: 'biznes, tijorat' },
    { word: 'union', uz: 'kasaba uyushmasi' },
    { word: 'charity', uz: 'xayriya tashkiloti' },
    { word: 'back out', synonym: 'withdraw', uz: 'va\'dadan qaytmoq' },
    { word: 'bring out', synonym: 'launch', uz: 'chiqarmoq (mahsulot)' },
    { word: 'close down', synonym: 'shut down', uz: 'yopilmoq (kompaniya)' },
    { word: 'see through (to)', synonym: 'complete', uz: 'oxiriga yetkazmoq' },
    { word: 'see to', synonym: 'handle', uz: 'shug\'ullanmoq' },
    { word: 'set to', synonym: 'start energetically', uz: 'qat\'iyat bilan boshlamoq' },
    { word: 'set out', synonym: 'begin', uz: 'ishga kirishmoq' },
    { word: 'set up', synonym: 'establish', uz: 'tashkil etmoq' },
    { word: 'slow down', synonym: 'decelerate', uz: 'sekinlashtirmoq' },
    { word: 'speed up', synonym: 'accelerate', uz: 'tezlashtirmoq' },
    { word: 'stand in for', synonym: 'substitute for', uz: 'o\'rniga ishlamoq' },
    { word: 'take on', synonym: 'employ', uz: 'ishga olmoq' },
    { word: 'take over', synonym: 'acquire', uz: 'nazoratni qo\'lga olmoq' },
    { word: 'turn down', synonym: 'reject', uz: 'rad etmoq' },
    { word: 'agreement', synonym: 'accord', uz: 'kelishuv' },
    { word: 'arrangement', synonym: 'plan', uz: 'kelishuv, reja' },
    { word: 'complaint', synonym: 'grievance', uz: 'shikoyat' },
    { word: 'day', uz: 'kun' },
    { word: 'decision', synonym: 'choice', uz: 'qaror' },
    { word: 'duty', synonym: 'obligation', uz: 'burch, vazifa' },
    { word: 'effort', synonym: 'endeavour', uz: 'harakat' },
    { word: 'experience', synonym: 'expertise', uz: 'tajriba' },
    { word: 'hold', synonym: 'pause', uz: 'kutish (telefon)' },
    { word: 'interest', synonym: 'concern', uz: 'qiziqish' },
    { word: 'interview', synonym: 'meeting', uz: 'suhbat (ish)' },
    { word: 'absent from', synonym: 'away from', uz: 'yo\'q, qatnashmagan' },
    { word: 'apply for', synonym: 'request', uz: 'ariza bermoq' },
    { word: 'attach', synonym: 'fasten', uz: 'biriktirmoq' },
    { word: 'begin', synonym: 'start', uz: 'boshlamoq' },
    { word: 'depend on', synonym: 'rely on', uz: 'bog\'liq bo\'lmoq' },
    { word: 'experienced in/at', synonym: 'skilled in', uz: 'tajribali' },
    { word: 'good for/at', synonym: 'skilled at', uz: 'yaxshi, mos' },
    { word: 'qualify as/in', synonym: 'become qualified', uz: 'malaka olmoq' },
    { word: 'responsible for', synonym: 'in charge of', uz: 'mas\'ul' },
    { word: 'specialise in', synonym: 'focus on', uz: 'ixtisoslashmoq' },
    { word: 'train to do', synonym: 'prepare', uz: 'o\'qitilmoq, tayyorlanmoq' },
    { word: 'work as/at/in', synonym: 'be employed as', uz: 'ishlamoq' },
    { word: 'add', synonym: 'increase', uz: 'qo\'shmoq' },
    { word: 'apply', synonym: 'request', uz: 'ariza bermoq' },
    { word: 'commerce', synonym: 'trade', uz: 'tijorat' },
    { word: 'dedicate', synonym: 'devote', uz: 'bag\'ishlamoq' },
    { word: 'effect', synonym: 'impact', uz: 'ta\'sir' },
    { word: 'employ', synonym: 'hire', uz: 'ishga olmoq' },
    { word: 'help', synonym: 'assist', uz: 'yordam bermoq' },
    { word: 'industry', synonym: 'manufacturing', uz: 'sanoat' },
    { word: 'machine', synonym: 'device', uz: 'mashina' },
    { word: 'manage', synonym: 'run', uz: 'boshqarmoq' },
    { word: 'meet', synonym: 'encounter', uz: 'uchrashmoq' },
    { word: 'profession', synonym: 'occupation', uz: 'kasb' },
    { word: 'qualify', synonym: 'certify', uz: 'malaka olmoq' },
    { word: 'responsible', synonym: 'accountable', uz: 'mas\'ul' },
    { word: 'supervise', synonym: 'oversee', uz: 'nazorat qilmoq' },
  ] },
];

export default VOCAB_RACE_UNITS_DESTINATION_B2;
