/**
 * Word Sprint vocabulary bank: the 14 units of Destination B1 vocabulary
 * Jamshid teaches from (word, part of speech, a synonym, and the Uzbek
 * translation). Each unit is asked as a whole -- see services/VocabRaceHub.js
 * for how these become multiple-choice questions.
 */

export const VOCAB_RACE_UNITS = [
  { num: 3, title: 'Fun and games', words: [
    { word: 'beat', pos: 'v', synonym: 'defeat', uz: 'yutmoq, mag\'lub etmoq' },
    { word: 'board game', pos: 'n phr', synonym: 'tabletop game', uz: 'stol o\'yini' },
    { word: 'captain', pos: 'n', synonym: 'leader', uz: 'kapitan, sardor' },
    { word: 'challenge', pos: 'v, n', synonym: 'dare / test', uz: 'da\'vat qilmoq / qiyin vazifa' },
    { word: 'champion', pos: 'n', synonym: 'winner', uz: 'chempion, g\'olib' },
    { word: 'cheat', pos: 'v', synonym: 'deceive', uz: 'aldamoq, firibgarlik qilmoq' },
    { word: 'classical music', pos: 'n phr', synonym: 'orchestral music', uz: 'klassik musiqa' },
    { word: 'club', pos: 'n', synonym: 'society', uz: 'klub, jamiyat' },
    { word: 'coach', pos: 'n', synonym: 'trainer', uz: 'murabbiy' },
    { word: 'competition', pos: 'n', synonym: 'contest', uz: 'musobaqa, tanlov' },
    { word: 'concert', pos: 'n', synonym: 'performance', uz: 'konsert' },
    { word: 'defeat', pos: 'v, n', synonym: 'overcome / loss', uz: 'mag\'lub etmoq / mag\'lubiyat' },
    { word: 'entertaining', pos: 'adj', synonym: 'enjoyable', uz: 'qiziqarli, ko\'ngilochar' },
    { word: 'folk music', pos: 'n phr', synonym: 'traditional music', uz: 'xalq musiqasi' },
    { word: 'group', pos: 'n', synonym: 'band', uz: 'guruh' },
    { word: 'gym', pos: 'n', synonym: 'fitness centre', uz: 'sport zali' },
    { word: 'have fun', pos: 'v phr', synonym: 'enjoy oneself', uz: 'yaxshi vaqt o\'tkazmoq' },
    { word: 'interest', pos: 'v, n', synonym: 'fascinate / hobby', uz: 'qiziqtirmoq / qiziqish' },
    { word: 'member', pos: 'n', synonym: 'participant', uz: 'a\'zo' },
    { word: 'opponent', pos: 'n', synonym: 'rival', uz: 'raqib' },
    { word: 'organise', pos: 'v', synonym: 'arrange', uz: 'tashkil qilmoq' },
    { word: 'pleasure', pos: 'n', synonym: 'enjoyment', uz: 'zavq, xursandchilik' },
    { word: 'referee', pos: 'n', synonym: 'umpire', uz: 'hakam, sudya' },
    { word: 'rhythm', pos: 'n', synonym: 'beat', uz: 'ritm, ohang' },
    { word: 'risk', pos: 'v, n', synonym: 'gamble / danger', uz: 'xavf ostiga qo\'ymoq / xavf, tavakkal' },
    { word: 'score', pos: 'v, n', synonym: 'gain points / result', uz: 'ochko to\'plamoq / hisob, natija' },
    { word: 'support', pos: 'v, n', synonym: 'back / backing', uz: 'qo\'llab- quvvatlamoq / qo\'llab-quvvatlash' },
    { word: 'team', pos: 'n', synonym: 'squad', uz: 'jamoa, guruh' },
    { word: 'train', pos: 'v', synonym: 'practise', uz: 'mashq qilmoq, tayyorgarlik ko\'rmoq' },
    { word: 'video game', pos: 'n phr', synonym: 'computer game', uz: 'video o\'yin' },
    { word: 'carry on', pos: 'phrasal v', synonym: 'continue', uz: 'davom ettirmoq' },
    { word: 'eat out', pos: 'phrasal v', synonym: 'eat at a restaurant', uz: 'tashqarida ovqatlanmoq (restoranda)' },
    { word: 'give up', pos: 'phrasal v', synonym: 'stop doing sth you do regularly', uz: 'tashlamoq, voz kechmoq' },
    { word: 'join in', pos: 'phrasal v', synonym: 'participate, take part', uz: 'qo\'shilmoq, ishtirok etmoq' },
    { word: 'send off', pos: 'phrasal v', synonym: 'make a player leave a game', uz: 'o\'yindan chetlatmoq' },
    { word: 'take up', pos: 'phrasal v', synonym: 'start (a hobby, sport, etc)', uz: 'shug\'ullana boshlamoq' },
    { word: 'turn down', pos: 'phrasal v', synonym: 'lower the volume of', uz: 'ovozini pasaytirmoq' },
    { word: 'turn up', pos: 'phrasal v', synonym: 'increase the volume of', uz: 'ovozini balandlatmoq' },
    { word: 'for a long time', pos: 'prep phr', synonym: 'for a long period', uz: 'uzoq vaqt davomida' },
    { word: 'for fun', pos: 'prep phr', synonym: 'for enjoyment', uz: 'ko\'ngil ochish uchun' },
    { word: 'in the middle (of)', pos: 'prep phr', synonym: 'in the centre of, during', uz: 'o\'rtasida, davomida' },
    { word: 'in time (for)', pos: 'prep phr', synonym: 'early enough (for)', uz: 'vaqtida (biror narsaga)' },
    { word: 'on CD/DVD/video', pos: 'prep phr', synonym: 'recorded on a disc', uz: 'diskda (CD/DVD/videoda)' },
    { word: 'on stage', pos: 'prep phr', synonym: 'performing in front of an audience', uz: 'sahnada' },
    { word: 'act', pos: 'word family', synonym: 'action, (in)active, actor', uz: 'harakat qilmoq (va turdosh so\'zlar)' },
    { word: 'athlete', pos: 'word family', synonym: 'athletic, athletics', uz: 'sportchi (va turdosh so\'zlar)' },
    { word: 'child', pos: 'word family', synonym: 'children, childhood', uz: 'bola (va turdosh so\'zlar)' },
    { word: 'collect', pos: 'word family', synonym: 'collection, collector', uz: 'to\'plamoq (va turdosh so\'zlar)' },
    { word: 'entertain', pos: 'word family', synonym: 'entertainment', uz: 'ko\'ngil ochmoq (va turdosh so\'z)' },
    { word: 'hero', pos: 'word family', synonym: 'heroic, heroine', uz: 'qahramon (va turdosh so\'zlar)' },
    { word: 'music', pos: 'word family', synonym: 'musical, musician', uz: 'musiqa (va turdosh so\'zlar)' },
    { word: 'play', pos: 'word family', synonym: 'player, playful', uz: 'o\'ynamoq (va turdosh so\'zlar)' },
    { word: 'sail', pos: 'word family', synonym: 'sailing, sailor', uz: 'suzmoq (kema bilan) (va turdosh so\'zlar)' },
    { word: 'sing', pos: 'word family', synonym: 'sang, sung, song, singer, singing', uz: 'qo\'shiq aytmoq (va turdosh so\'zlar)' },
  ]},
  { num: 6, title: 'Learning and doing', words: [
    { word: 'achieve', pos: 'v', synonym: 'accomplish', uz: 'erishmoq, amalga oshirmoq' },
    { word: 'brain', pos: 'n', synonym: 'mind', uz: 'miya' },
    { word: 'clever', pos: 'adj', synonym: 'intelligent', uz: 'aqlli, zukko' },
    { word: 'concentrate', pos: 'v', synonym: 'focus', uz: 'diqqatni jamlamoq' },
    { word: 'consider', pos: 'v', synonym: 'think about', uz: 'o\'ylab ko\'rmoq, hisobga olmoq' },
    { word: 'course', pos: 'n', synonym: 'class', uz: 'kurs' },
    { word: 'degree', pos: 'n', synonym: 'qualification', uz: 'diplom, daraja' },
    { word: 'experience', pos: 'v, n', synonym: 'undergo / knowledge', uz: 'boshdan kechirmoq / tajriba' },
    { word: 'expert', pos: 'n, adj', synonym: 'specialist', uz: 'mutaxassis' },
    { word: 'fail', pos: 'v', synonym: 'not succeed', uz: 'yiqilmoq, muvaffaqiyatsizlikka uchramoq' },
    { word: 'guess', pos: 'v, n', synonym: 'estimate', uz: 'taxmin qilmoq / taxmin' },
    { word: 'hesitate', pos: 'v', synonym: 'pause', uz: 'ikkilanmoq' },
    { word: 'instruction', pos: 'n', synonym: 'direction', uz: 'ko\'rsatma' },
    { word: 'make progress', pos: 'v phr', synonym: 'improve', uz: 'taraqqiy qilmoq, rivojlanmoq' },
    { word: 'make sure', pos: 'v phr', synonym: 'ensure', uz: 'ishonch hosil qilmoq' },
    { word: 'mark', pos: 'v, n', synonym: 'grade', uz: 'baholamoq / baho' },
    { word: 'mental', pos: 'adj', synonym: 'psychological', uz: 'aqliy, ruhiy' },
    { word: 'pass', pos: 'v', synonym: 'succeed in', uz: '(imtihondan) o\'tmoq' },
    { word: 'qualification', pos: 'n', synonym: 'certificate', uz: 'malaka, kvalifikatsiya' },
    { word: 'remind', pos: 'v', synonym: 'prompt', uz: 'eslatmoq' },
    { word: 'report', pos: 'n', synonym: 'account', uz: 'hisobot' },
    { word: 'revise', pos: 'v', synonym: 'review', uz: 'takrorlamoq' },
    { word: 'search', pos: 'v, n', synonym: 'look for', uz: 'qidirmoq / qidiruv' },
    { word: 'skill', pos: 'n', synonym: 'ability', uz: 'mahorat, ko\'nikma' },
    { word: 'smart', pos: 'adj', synonym: 'intelligent', uz: 'aqlli, zukko' },
    { word: 'subject', pos: 'n', synonym: 'topic', uz: 'fan, mavzu' },
    { word: 'take an exam', pos: 'v phr', synonym: 'sit a test', uz: 'imtihon topshirmoq' },
    { word: 'talented', pos: 'adj', synonym: 'gifted', uz: 'iqtidorli, iste\'dodli' },
    { word: 'term', pos: 'n', synonym: 'semester', uz: 'o\'quv chorak/semestri' },
    { word: 'cross out', pos: 'phrasal v', synonym: 'draw a line through sth written', uz: 'chizib tashlamoq (yozuvni)' },
    { word: 'look up', pos: 'phrasal v', synonym: 'try to find information in a book, etc', uz: 'qidirib topmoq (lug\'atda, kitobda)' },
    { word: 'point out', pos: 'phrasal v', synonym: 'tell sb important information', uz: 'e\'tiborini qaratmoq, ta\'kidlamoq' },
    { word: 'read out', pos: 'phrasal v', synonym: 'say sth out loud which you are reading', uz: 'ovoz chiqarib o\'qimoq' },
    { word: 'rip up', pos: 'phrasal v', synonym: 'tear into pieces', uz: 'yirtib tashlamoq (bo\'laklarga)' },
    { word: 'rub out', pos: 'phrasal v', synonym: 'remove with a rubber', uz: 'o\'chirmoq (o\'chirg\'ich bilan)' },
    { word: 'turn over', pos: 'phrasal v', synonym: 'turn sth so the other side is towards you', uz: 'varaqlamoq, ag\'darmoq' },
    { word: 'write down', pos: 'phrasal v', synonym: 'write information on a piece of paper', uz: 'yozib olmoq' },
    { word: 'by heart', pos: 'prep phr', synonym: 'from memory', uz: 'yod olib (yoddan)' },
    { word: 'for instance', pos: 'prep phr', synonym: 'for example', uz: 'masalan' },
    { word: 'in conclusion', pos: 'prep phr', synonym: 'finally, to sum up', uz: 'xulosa qilib aytganda' },
    { word: 'in fact', pos: 'prep phr', synonym: 'actually', uz: 'aslida' },
    { word: 'in favour (of)', pos: 'prep phr', synonym: 'supporting', uz: 'tarafdor, foydasiga' },
    { word: 'in general', pos: 'prep phr', synonym: 'generally, on the whole', uz: 'umuman olganda' },
    { word: 'begin', pos: 'word family', synonym: 'began, begun, beginner, beginning', uz: 'boshlamoq (va turdosh so\'zlar)' },
    { word: 'brave', pos: 'word family', synonym: 'bravery', uz: 'jasur (va turdosh so\'z)' },
    { word: 'correct', pos: 'word family', synonym: 'correction, incorrect', uz: 'to\'g\'ri (va turdosh so\'zlar)' },
    { word: 'divide', pos: 'word family', synonym: 'division', uz: 'bo\'lmoq (va turdosh so\'z)' },
    { word: 'educate', pos: 'word family', synonym: 'education', uz: 'ta\'lim bermoq (va turdosh so\'z)' },
    { word: 'instruct', pos: 'word family', synonym: 'instruction, instructor', uz: 'o\'rgatmoq (va turdosh so\'zlar)' },
    { word: 'memory', pos: 'word family', synonym: 'memorise, memorial', uz: 'xotira (va turdosh so\'zlar)' },
    { word: 'refer', pos: 'word family', synonym: 'reference', uz: 'murojaat qilmoq (va turdosh so\'z)' },
    { word: 'silent', pos: 'word family', synonym: 'silence, silently', uz: 'jim (va turdosh so\'zlar)' },
    { word: 'simple', pos: 'word family', synonym: 'simplify, simplicity', uz: 'oddiy (va turdosh so\'zlar)' },
  ]},
  { num: 9, title: 'Coming and going', words: [
    { word: 'abroad', pos: 'adv', synonym: 'overseas', uz: 'chet elda / chet elga' },
    { word: 'accommodation', pos: 'n', synonym: 'lodging', uz: 'turar joy, yashash joyi' },
    { word: 'book', pos: 'v', synonym: 'reserve', uz: 'bron qilmoq' },
    { word: 'cancel', pos: 'v', synonym: 'call off', uz: 'bekor qilmoq' },
    { word: 'catch', pos: 'v', synonym: 'board', uz: '(transportga) ulgurmoq' },
    { word: 'convenient', pos: 'adj', synonym: 'suitable', uz: 'qulay' },
    { word: 'crash', pos: 'v', synonym: 'collide', uz: 'to\'qnashmoq, halokatga uchramoq' },
    { word: 'crowded', pos: 'adj', synonym: 'packed', uz: 'gavjum, odam ko\'p' },
    { word: 'cruise', pos: 'n', synonym: 'sea voyage', uz: 'dengiz sayohati, kruiz' },
    { word: 'delay', pos: 'v, n', synonym: 'postpone / holdup', uz: 'kechiktirmoq / kechikish' },
    { word: 'destination', pos: 'n', synonym: 'endpoint', uz: 'manzil' },
    { word: 'ferry', pos: 'n', synonym: 'boat', uz: 'parom' },
    { word: 'flight', pos: 'n', synonym: 'plane journey', uz: 'parvoz' },
    { word: 'harbour', pos: 'n', synonym: 'port', uz: 'port, langargoh' },
    { word: 'journey', pos: 'n', synonym: 'trip', uz: 'sayohat, safar' },
    { word: 'luggage', pos: 'n', synonym: 'baggage', uz: 'yuk, baggaj' },
    { word: 'nearby', pos: 'adj, adv', synonym: 'close', uz: 'yaqin, yaqin atrofda' },
    { word: 'pack', pos: 'v', synonym: 'fill a bag', uz: 'yig\'ishtirmoq (jomadonga)' },
    { word: 'passport', pos: 'n', synonym: 'travel document', uz: 'pasport' },
    { word: 'platform', pos: 'n', synonym: 'railway platform', uz: 'platforma, peron' },
    { word: 'public transport', pos: 'n phr', synonym: 'mass transit', uz: 'jamoat transporti' },
    { word: 'reach', pos: 'v', synonym: 'arrive at', uz: 'yetib bormoq' },
    { word: 'resort', pos: 'n', synonym: 'holiday destination', uz: 'kurort' },
    { word: 'souvenir', pos: 'n', synonym: 'keepsake', uz: 'esdalik sovg\'a' },
    { word: 'traffic', pos: 'n', synonym: 'vehicles', uz: 'transport harakati, tirbandlik' },
    { word: 'vehicle', pos: 'n', synonym: 'automobile', uz: 'transport vositasi' },
    { word: 'get in(to)', pos: 'phrasal v', synonym: 'enter a car', uz: '(mashinaga) kirmoq, o\'tirmoq' },
    { word: 'get off', pos: 'phrasal v', synonym: 'leave a bus/train/etc', uz: '(transportdan) tushmoq' },
    { word: 'get on(to)', pos: 'phrasal v', synonym: 'enter a bus/train/etc', uz: '(transportga) chiqmoq, minmoq' },
    { word: 'get out (of)', pos: 'phrasal v', synonym: 'leave a car/building/room/etc', uz: '(mashinadan, binodan) chiqmoq' },
    { word: 'go away', pos: 'phrasal v', synonym: 'leave a place/sb', uz: 'ketmoq, uzoqlashmoq' },
    { word: 'go back (to)', pos: 'phrasal v', synonym: 'return (to)', uz: 'qaytmoq' },
    { word: 'set off', pos: 'phrasal v', synonym: 'start a journey', uz: 'yo\'lga chiqmoq' },
    { word: 'take off', pos: 'phrasal v', synonym: 'leave the ground', uz: 'parvoz qilmoq (uchishga)' },
    { word: 'by air/sea/bus/car/etc', pos: 'prep phr', synonym: 'using a means of transport', uz: '(transport turi) orqali' },
    { word: 'on board', pos: 'prep phr', synonym: 'on a ship/plane/train', uz: 'bortda (kema, samolyot)' },
    { word: 'on foot', pos: 'prep phr', synonym: 'walking', uz: 'piyoda' },
    { word: 'on holiday', pos: 'prep phr', synonym: 'on vacation', uz: 'ta\'tilda' },
    { word: 'on schedule', pos: 'prep phr', synonym: 'on time, as planned', uz: 'reja bo\'yicha, jadval asosida' },
    { word: 'on the coast', pos: 'prep phr', synonym: 'by the sea', uz: 'qirg\'oqda (dengiz bo\'yida)' },
    { word: 'attract', pos: 'word family', synonym: 'attractive, attraction', uz: 'jalb qilmoq (va turdosh so\'zlar)' },
    { word: 'back', pos: 'word family', synonym: 'backwards', uz: 'orqa (va turdosh so\'z)' },
    { word: 'choose', pos: 'word family', synonym: 'chose, chosen, choice', uz: 'tanlamoq (va turdosh so\'zlar)' },
    { word: 'comfort', pos: 'word family', synonym: '(un)comfortable', uz: 'qulaylik (va turdosh so\'z)' },
    { word: 'depart', pos: 'word family', synonym: 'departure', uz: 'jo\'namoq (va turdosh so\'z)' },
    { word: 'direct', pos: 'word family', synonym: 'direction', uz: 'to\'g\'ridan-to\'g\'ri (va turdosh so\'z)' },
    { word: 'drive', pos: 'word family', synonym: 'drove, driven, driver', uz: 'haydamoq (va turdosh so\'zlar)' },
    { word: 'fly', pos: 'word family', synonym: 'flew, flown, flight', uz: 'uchmoq (va turdosh so\'zlar)' },
    { word: 'travel', pos: 'word family', synonym: 'traveller', uz: 'sayohat qilmoq (va turdosh so\'z)' },
    { word: 'visit', pos: 'word family', synonym: 'visitor', uz: 'tashrif buyurmoq (va turdosh so\'z)' },
  ]},
  { num: 12, title: 'Friends and relations', words: [
    { word: 'apologise', pos: 'v', synonym: 'say sorry', uz: 'uzr so\'ramoq' },
    { word: 'boyfriend', pos: 'n', synonym: 'partner', uz: 'yigit (sevgilisi)' },
    { word: 'close', pos: 'adj', synonym: 'intimate', uz: 'yaqin' },
    { word: 'confident', pos: 'adj', synonym: 'self-assured', uz: 'o\'ziga ishonchli' },
    { word: 'couple', pos: 'n', synonym: 'pair', uz: 'er-xotin, juftlik' },
    { word: 'decorate', pos: 'v', synonym: 'adorn', uz: 'bezamoq' },
    { word: 'defend', pos: 'v', synonym: 'protect', uz: 'himoya qilmoq' },
    { word: 'divorced', pos: 'adj', synonym: 'separated', uz: 'ajrashgan' },
    { word: 'flat', pos: 'n', synonym: 'apartment', uz: 'kvartira' },
    { word: 'generous', pos: 'adj', synonym: 'giving', uz: 'saxiy' },
    { word: 'girlfriend', pos: 'n', synonym: 'partner', uz: 'qiz (sevgilisi)' },
    { word: 'grateful', pos: 'adj', synonym: 'thankful', uz: 'minnatdor' },
    { word: 'guest', pos: 'n', synonym: 'visitor', uz: 'mehmon' },
    { word: 'independent', pos: 'adj', synonym: 'self-reliant', uz: 'mustaqil' },
    { word: 'introduce', pos: 'v', synonym: 'present', uz: 'tanishtirmoq' },
    { word: 'loving', pos: 'adj', synonym: 'affectionate', uz: 'mehribon, sevgi to\'la' },
    { word: 'loyal', pos: 'adj', synonym: 'faithful', uz: 'sodiq' },
    { word: 'mood', pos: 'n', synonym: 'state of mind', uz: 'kayfiyat' },
    { word: 'neighbourhood', pos: 'n', synonym: 'district', uz: 'mahalla, atrof- hudud' },
    { word: 'ordinary', pos: 'adj', synonym: 'normal', uz: 'oddiy' },
    { word: 'patient', pos: 'adj', synonym: 'tolerant', uz: 'sabrli' },
    { word: 'private', pos: 'adj', synonym: 'personal', uz: 'shaxsiy, maxfiy' },
    { word: 'recognise', pos: 'v', synonym: 'identify', uz: 'tanimoq' },
    { word: 'relation', pos: 'n', synonym: 'relationship', uz: 'munosabat, qarindosh' },
    { word: 'rent', pos: 'v, n', synonym: 'lease / hire fee', uz: 'ijaraga olmoq / ijara haqi' },
    { word: 'respect', pos: 'v, n', synonym: 'admire / esteem', uz: 'hurmat qilmoq / hurmat' },
    { word: 'single', pos: 'adj', synonym: 'unmarried', uz: 'yolg\'iz, turmush qurmagan' },
    { word: 'stranger', pos: 'n', synonym: 'unknown person', uz: 'notanish odam' },
    { word: 'trust', pos: 'v, n', synonym: 'rely on / confidence', uz: 'ishonmoq / ishonch' },
    { word: 'bring up', pos: 'phrasal v', synonym: 'take care of a child until he or she becomes an adult', uz: 'tarbiyalamoq (bolani)' },
    { word: 'fall out (with)', pos: 'phrasal v', synonym: 'have an argument with sb and stop being friends', uz: 'araz qilmoq, ajrashib qolmoq (do\'stlik)' },
    { word: 'get on (with)', pos: 'phrasal v', synonym: 'have a good relationship (with)', uz: 'chiqishmoq, yaxshi munosabatda bo\'lmoq' },
    { word: 'go out with', pos: 'phrasal v', synonym: 'be the boyfriend/girlfriend of', uz: 'uchrashmoq (sevgilisi bo\'lmoq)' },
    { word: 'grow up', pos: 'phrasal v', synonym: 'become older (for children)', uz: 'voyaga yetmoq, o\'smoq' },
    { word: 'let down', pos: 'phrasal v', synonym: 'disappoint', uz: 'umidini oqlamaslik, xafa qilmoq' },
    { word: 'look after', pos: 'phrasal v', synonym: 'take care of', uz: 'g\'amxo\'rlik qilmoq, qaramoq' },
    { word: 'split up', pos: 'phrasal v', synonym: 'end a relationship', uz: 'ajrashmoq (munosabatni tugatmoq)' },
    { word: 'by yourself', pos: 'prep phr', synonym: 'alone', uz: 'yolg\'iz o\'zi' },
    { word: 'in common (with)', pos: 'prep phr', synonym: 'sharing the same interests/qualities', uz: 'umumiylikka ega (bilan)' },
    { word: 'in contact (with)', pos: 'prep phr', synonym: 'communicating (with)', uz: 'aloqada (bilan)' },
    { word: 'in love (with)', pos: 'prep phr', synonym: 'loving (sb)', uz: 'sevib qolgan (kimnidir)' },
    { word: 'on purpose', pos: 'prep phr', synonym: 'deliberately', uz: 'ataylab' },
    { word: 'on your own', pos: 'prep phr', synonym: 'alone, without help', uz: 'yolg\'iz, yordamisiz' },
    { word: 'able', pos: 'word family', synonym: 'ability, disabled, unable', uz: 'qodir (va turdosh so\'zlar)' },
    { word: 'admire', pos: 'word family', synonym: 'admiration', uz: 'hayratlanmoq (va turdosh so\'z)' },
    { word: 'care', pos: 'word family', synonym: 'careful, careless', uz: 'g\'amxo\'rlik (va turdosh so\'zlar)' },
    { word: 'forgive', pos: 'word family', synonym: 'forgave, forgiven, forgiveness', uz: 'kechirmoq (va turdosh so\'zlar)' },
    { word: 'honest', pos: 'word family', synonym: 'dishonest, honesty', uz: 'halol (va turdosh so\'zlar)' },
    { word: 'lie', pos: 'word family', synonym: 'liar, lying', uz: 'yolg\'on gapirmoq (va turdosh so\'zlar)' },
    { word: 'person', pos: 'word family', synonym: 'personality, personal', uz: 'shaxs (va turdosh so\'zlar)' },
    { word: 'relate', pos: 'word family', synonym: 'relative, relation, relationship', uz: 'bog\'liq bo\'lmoq (va turdosh so\'zlar)' },
  ]},
  { num: 15, title: 'Buying and selling', words: [
    { word: 'advertisement', pos: 'n', synonym: 'ad', uz: 'reklama' },
    { word: 'afford', pos: 'v', synonym: 'be able to pay for', uz: 'pul yetkazmoq (xarid uchun)' },
    { word: 'bargain', pos: 'n', synonym: 'good deal', uz: 'arzon xarid, kelishuv' },
    { word: 'brand', pos: 'n', synonym: 'make', uz: 'brend, marka' },
    { word: 'catalogue', pos: 'n', synonym: 'brochure', uz: 'katalog' },
    { word: 'change', pos: 'n', synonym: 'coins returned', uz: 'qaytim (pul)' },
    { word: 'coin', pos: 'n', synonym: 'currency piece', uz: 'tanga' },
    { word: 'cost', pos: 'v, n', synonym: 'be priced at / price', uz: 'turmoq (narxda) / narx' },
    { word: 'customer', pos: 'n', synonym: 'client', uz: 'mijoz' },
    { word: 'debt', pos: 'n', synonym: 'money owed', uz: 'qarz' },
    { word: 'demand', pos: 'v', synonym: 'require strongly', uz: 'talab qilmoq' },
    { word: 'export', pos: 'v', synonym: 'sell abroad', uz: 'eksport qilmoq' },
    { word: 'fee', pos: 'n', synonym: 'charge', uz: 'to\'lov, haq' },
    { word: 'fortune', pos: 'n', synonym: 'a great deal of money', uz: 'boylik, katta pul' },
    { word: 'import', pos: 'v', synonym: 'bring in goods', uz: 'import qilmoq' },
    { word: 'invest', pos: 'v', synonym: 'put money into', uz: 'sarmoya kiritmoq' },
    { word: 'obtain', pos: 'v', synonym: 'get', uz: 'olmoq, qo\'lga kiritmoq' },
    { word: 'owe', pos: 'v', synonym: 'be in debt for', uz: 'qarzdor bo\'lmoq' },
    { word: 'own', pos: 'v', synonym: 'possess', uz: 'egalik qilmoq' },
    { word: 'profit', pos: 'n', synonym: 'gain', uz: 'foyda' },
    { word: 'property', pos: 'n', synonym: 'real estate', uz: 'mulk, ko\'chmas mulk' },
    { word: 'purchase', pos: 'v, n', synonym: 'buy / acquisition', uz: 'sotib olmoq / xarid' },
    { word: 'receipt', pos: 'n', synonym: 'proof of purchase', uz: 'kvitansiya, chek' },
    { word: 'require', pos: 'v', synonym: 'need', uz: 'talab qilmoq, zarur bo\'lmoq' },
    { word: 'sale', pos: 'n', synonym: 'discount event', uz: 'chegirma savdosi, sotuv' },
    { word: 'save', pos: 'v', synonym: 'put money aside', uz: 'jamg\'armoq, tejamoq' },
    { word: 'select', pos: 'v', synonym: 'choose', uz: 'tanlamoq' },
    { word: 'supply', pos: 'v, n', synonym: 'provide / stock', uz: 'ta\'minlamoq / ta\'minot' },
    { word: 'variety', pos: 'n', synonym: 'range', uz: 'xillar, turlar' },
    { word: 'waste', pos: 'v, n', synonym: 'squander / rubbish', uz: 'isrof qilmoq / chiqindi' },
    { word: 'add up', pos: 'phrasal v', synonym: 'find the total of', uz: 'qo\'shib hisoblamoq' },
    { word: 'come back (from)', pos: 'phrasal v', synonym: 'return (from)', uz: 'qaytmoq (dan)' },
    { word: 'give away', pos: 'phrasal v', synonym: 'give sth free of charge', uz: 'bepul tarqatmoq, sovg\'a qilmoq' },
    { word: 'hurry up', pos: 'phrasal v', synonym: 'do sth more quickly', uz: 'shoshilmoq, tezlashtirmoq' },
    { word: 'pay back', pos: 'phrasal v', synonym: 'return money (to sb)', uz: 'qarzni qaytarmoq' },
    { word: 'save up (for)', pos: 'phrasal v', synonym: 'save money (for a specific purpose)', uz: 'pul jamg\'armoq (biror narsa uchun)' },
    { word: 'take back', pos: 'phrasal v', synonym: 'return sth to the place it came from', uz: 'qaytarib bermoq (do\'konga)' },
    { word: 'take down', pos: 'phrasal v', synonym: 'remove (from a high place)', uz: 'tushirmoq (yuqoridan)' },
    { word: 'by credit card/cheque', pos: 'prep phr', synonym: 'using a card/cheque to pay', uz: 'kredit karta/chek orqali' },
    { word: 'for rent', pos: 'prep phr', synonym: 'available to rent', uz: 'ijaraga (beriladigan)' },
    { word: 'for sale', pos: 'prep phr', synonym: 'available to buy', uz: 'sotuvda' },
    { word: 'in cash', pos: 'prep phr', synonym: 'using money notes/coins', uz: 'naqd pulda' },
    { word: 'in debt', pos: 'prep phr', synonym: 'owing money', uz: 'qarzdor' },
    { word: 'in good/bad condition', pos: 'prep phr', synonym: 'in a good/poor state', uz: 'yaxshi/yomon holatda' },
    { word: 'add', pos: 'word family', synonym: 'addition', uz: 'qo\'shmoq (va turdosh so\'z)' },
    { word: 'compare', pos: 'word family', synonym: 'comparison', uz: 'solishtirmoq (va turdosh so\'z)' },
    { word: 'decide', pos: 'word family', synonym: 'decision', uz: 'qaror qilmoq (va turdosh so\'z)' },
    { word: 'expense', pos: 'word family', synonym: '(in)expensive', uz: 'xarajat (va turdosh so\'z)' },
    { word: 'judge', pos: 'word family', synonym: 'judgement', uz: 'baholamoq, hukm qilmoq (va turdosh so\'z)' },
    { word: 'serve', pos: 'word family', synonym: 'service, servant', uz: 'xizmat qilmoq (va turdosh so\'zlar)' },
    { word: 'true', pos: 'word family', synonym: 'truth, untrue, truthful', uz: 'to\'g\'ri, haqiqiy (va turdosh so\'zlar)' },
    { word: 'use', pos: 'word family', synonym: 'useful, useless', uz: 'foydalanmoq (va turdosh so\'zlar)' },
    { word: 'value', pos: 'word family', synonym: 'valuable', uz: 'qiymat (va turdosh so\'z)' },
  ]},
  { num: 18, title: 'Inventions and discoveries', words: [
    { word: 'artificial', pos: 'adj', synonym: 'man-made', uz: 'sun\'iy' },
    { word: 'automatic', pos: 'adj', synonym: 'self-operating', uz: 'avtomatik' },
    { word: 'complicated', pos: 'adj', synonym: 'complex', uz: 'murakkab' },
    { word: 'decrease', pos: 'v, n', synonym: 'reduce / decline', uz: 'kamaymoq, kamaytirmoq / kamayish' },
    { word: 'digital', pos: 'adj', synonym: 'electronic', uz: 'raqamli' },
    { word: 'discover', pos: 'v', synonym: 'find out', uz: 'kashf qilmoq' },
    { word: 'effect', pos: 'n', synonym: 'result', uz: 'ta\'sir, natija' },
    { word: 'equipment', pos: 'n', synonym: 'gear', uz: 'jihoz, uskuna' },
    { word: 'estimate', pos: 'v', synonym: 'calculate roughly', uz: 'taxmin qilmoq, baholamoq' },
    { word: 'exact', pos: 'adj', synonym: 'precise', uz: 'aniq' },
    { word: 'experiment', pos: 'v, n', synonym: 'test / trial', uz: 'tajriba o\'tkazmoq / tajriba' },
    { word: 'gadget', pos: 'n', synonym: 'device', uz: 'gadjet, moslama' },
    { word: 'hardware', pos: 'n', synonym: 'machinery', uz: 'apparat ta\'minoti' },
    { word: 'invent', pos: 'v', synonym: 'create', uz: 'ixtiro qilmoq' },
    { word: 'involve', pos: 'v', synonym: 'include', uz: 'o\'z ichiga olmoq, jalb qilmoq' },
    { word: 'laboratory', pos: 'n', synonym: 'lab', uz: 'laboratoriya' },
    { word: 'lack', pos: 'v, n', synonym: 'be without / shortage', uz: 'yetishmaslik, kamlik' },
    { word: 'laptop', pos: 'n', synonym: 'notebook computer', uz: 'noutbuk' },
    { word: 'maximum', pos: 'adj', synonym: 'highest possible', uz: 'maksimal, eng yuqori' },
    { word: 'minimum', pos: 'adj', synonym: 'lowest possible', uz: 'minimal, eng kam' },
    { word: 'operate', pos: 'v', synonym: 'work / run a machine', uz: 'boshqarmoq, ishlatmoq' },
    { word: 'plastic', pos: 'n, adj', synonym: 'synthetic material', uz: 'plastmassa' },
    { word: 'program', pos: 'v, n', synonym: 'code / software', uz: 'dasturlamoq / dastur' },
    { word: 'research', pos: 'n', synonym: 'investigation', uz: 'tadqiqot' },
    { word: 'run', pos: 'v', synonym: 'operate (a program)', uz: 'ishga tushirmoq (dastur haqida)' },
    { word: 'screen', pos: 'n', synonym: 'display', uz: 'ekran' },
    { word: 'software', pos: 'n', synonym: 'programs', uz: 'dasturiy ta\'minot' },
    { word: 'sudden', pos: 'adj', synonym: 'unexpected', uz: 'kutilmagan, to\'satdan' },
    { word: 'technology', pos: 'n', synonym: 'tech', uz: 'texnologiya' },
    { word: 'unique', pos: 'adj', synonym: 'one of a kind', uz: 'yagona, betakror' },
    { word: 'break down', pos: 'phrasal v', synonym: 'stop working (for a machine, etc)', uz: 'buzilmoq (mashina, uskuna)' },
    { word: 'come across', pos: 'phrasal v', synonym: 'find sth by chance', uz: 'tasodifan topib qolmoq' },
    { word: 'find out', pos: 'phrasal v', synonym: 'discover information, etc', uz: 'aniqlab olmoq, bilib olmoq' },
    { word: 'make up', pos: 'phrasal v', synonym: 'invent an explanation, excuse, etc', uz: 'o\'ylab topmoq (bahona, hikoya)' },
    { word: 'pull off', pos: 'phrasal v', synonym: 'break by pulling', uz: 'tortib uzib olmoq' },
    { word: 'throw away', pos: 'phrasal v', synonym: 'put sth in a rubbish bin', uz: 'tashlab yubormoq (chiqindi)' },
    { word: 'turn off', pos: 'phrasal v', synonym: 'stop a machine working', uz: 'o\'chirmoq (uskunani)' },
    { word: 'turn on', pos: 'phrasal v', synonym: 'start a machine working', uz: 'yoqmoq (uskunani)' },
    { word: 'at last', pos: 'prep phr', synonym: 'finally', uz: 'nihoyat' },
    { word: 'by chance', pos: 'prep phr', synonym: 'accidentally, unexpectedly', uz: 'tasodifan' },
    { word: 'in my opinion', pos: 'prep phr', synonym: 'I think that', uz: 'mening fikrimcha' },
    { word: 'in the end', pos: 'prep phr', synonym: 'eventually, finally', uz: 'oxir-oqibat' },
    { word: 'in the future', pos: 'prep phr', synonym: 'at a later time', uz: 'kelajakda' },
    { word: 'out of order', pos: 'prep phr', synonym: 'not working', uz: 'ishlamayapti (buzilgan)' },
    { word: 'boil', pos: 'word family', synonym: 'boiler, boiling', uz: 'qaynatmoq (va turdosh so\'zlar)' },
    { word: 'chemist', pos: 'word family', synonym: 'chemical, chemistry', uz: 'kimyogar (va turdosh so\'zlar)' },
    { word: 'conclude', pos: 'word family', synonym: 'conclusion', uz: 'xulosa qilmoq (va turdosh so\'z)' },
    { word: 'examine', pos: 'word family', synonym: 'exam(ination), examiner', uz: 'tekshirmoq (va turdosh so\'zlar)' },
    { word: 'fascinate', pos: 'word family', synonym: 'fascination, fascinating', uz: 'maftun etmoq (va turdosh so\'zlar)' },
    { word: 'history', pos: 'word family', synonym: 'historic, historian', uz: 'tarix (va turdosh so\'zlar)' },
    { word: 'identical', pos: 'word family', synonym: 'identically', uz: 'bir xil, aynan o\'xshash (va turdosh so\'z)' },
    { word: 'long', pos: 'word family', synonym: 'length', uz: 'uzun (va turdosh so\'z)' },
    { word: 'measure', pos: 'word family', synonym: 'measurement', uz: 'o\'lchamoq (va turdosh so\'z)' },
    { word: 'science', pos: 'word family', synonym: 'scientist', uz: 'fan (va turdosh so\'z)' },
  ]},
  { num: 21, title: 'Sending and receiving', words: [
    { word: 'accent', pos: 'n', synonym: 'pronunciation style', uz: 'talaffuz, aksent' },
    { word: 'announcement', pos: 'n', synonym: 'statement', uz: 'e\'lon' },
    { word: 'broadcast', pos: 'v, n', synonym: 'transmit / programme', uz: 'efirga uzatmoq / translyatsiya' },
    { word: 'channel', pos: 'n', synonym: 'station', uz: 'kanal' },
    { word: 'clear', pos: 'adj', synonym: 'understandable', uz: 'aniq, tushunarli' },
    { word: 'click', pos: 'v', synonym: 'press', uz: 'bosmoq (sichqonchani)' },
    { word: 'contact', pos: 'v, n', synonym: 'reach / connection', uz: 'bog\'lanmoq / aloqa' },
    { word: 'file', pos: 'n', synonym: 'document', uz: 'fayl, hujjat' },
    { word: 'formal', pos: 'adj', synonym: 'official', uz: 'rasmiy' },
    { word: 'image', pos: 'n', synonym: 'picture', uz: 'rasm, tasvir' },
    { word: 'informal', pos: 'adj', synonym: 'casual', uz: 'norasmiy' },
    { word: 'internet', pos: 'n', synonym: 'the net', uz: 'internet' },
    { word: 'interrupt', pos: 'v', synonym: 'cut in', uz: 'gapini bo\'lmoq' },
    { word: 'link', pos: 'v, n', synonym: 'connect / connection', uz: 'bog\'lamoq / havola' },
    { word: 'media', pos: 'n', synonym: 'press', uz: 'ommaviy axborot vositalari' },
    { word: 'mobile phone', pos: 'n phr', synonym: 'cell phone', uz: 'mobil telefon' },
    { word: 'online', pos: 'adj, adv', synonym: 'on the internet', uz: 'onlayn, internetda' },
    { word: 'pause', pos: 'v, n', synonym: 'stop briefly / break', uz: 'to\'xtatib turmoq / tanaffus' },
    { word: 'persuade', pos: 'v', synonym: 'convince', uz: 'ishontirmoq, ko\'ndirmoq' },
    { word: 'pronounce', pos: 'v', synonym: 'say aloud', uz: 'talaffuz qilmoq' },
    { word: 'publish', pos: 'v', synonym: 'print/release', uz: 'nashr etmoq' },
    { word: 'report', pos: 'v, n', synonym: 'announce / account', uz: 'xabar bermoq / hisobot' },
    { word: 'request', pos: 'v, n', synonym: 'ask for / appeal', uz: 'so\'ramoq / iltimos' },
    { word: 'ring', pos: 'v', synonym: 'call', uz: 'qo\'ng\'iroq qilmoq' },
    { word: 'signal', pos: 'n', synonym: 'sign', uz: 'signal, belgi' },
    { word: 'swear', pos: 'v', synonym: 'curse', uz: 'qasam ichmoq / haqoratli so\'z ishlatmoq' },
    { word: 'type', pos: 'v', synonym: 'key in', uz: 'yozmoq (klaviaturada)' },
    { word: 'viewer', pos: 'n', synonym: 'watcher', uz: 'tomoshabin' },
    { word: 'website', pos: 'n', synonym: 'site', uz: 'veb-sayt' },
    { word: 'whisper', pos: 'v, n', synonym: 'murmur', uz: 'pichirlamoq / pichirlash' },
    { word: 'call back', pos: 'phrasal v', synonym: 'ring again on the phone', uz: 'qayta qo\'ng\'iroq qilmoq' },
    { word: 'come out', pos: 'phrasal v', synonym: 'be published on the Internet', uz: 'chiqmoq, e\'lon qilinmoq' },
    { word: 'cut off', pos: 'phrasal v', synonym: 'disconnect (phone, electricity, etc)', uz: 'uzib qo\'ymoq (aloqa, elektr)' },
    { word: 'fill in', pos: 'phrasal v', synonym: 'add information in the spaces on a form, etc', uz: 'to\'ldirmoq (blank, forma)' },
    { word: 'hang up', pos: 'phrasal v', synonym: 'put the receiver down to end a phone call', uz: 'telefonni qo\'ymoq (suhbatni tugatish)' },
    { word: 'log off', pos: 'phrasal v', synonym: 'disconnect from the Internet/a website', uz: 'tizimdan chiqmoq' },
    { word: 'log on(to)', pos: 'phrasal v', synonym: 'connect to the Internet/a website', uz: 'tizimga kirmoq' },
    { word: 'print out', pos: 'phrasal v', synonym: 'make a paper copy of sth on a computer', uz: 'chop etmoq (printerda)' },
    { word: 'by e- mail/phone/letter', pos: 'prep phr', synonym: 'using a means of communication', uz: '(elektron pochta/telefon/xat) orqali' },
    { word: 'on the news', pos: 'prep phr', synonym: 'broadcast as news', uz: 'yangiliklarda' },
    { word: 'on the phone', pos: 'prep phr', synonym: 'talking by telephone', uz: 'telefonda' },
    { word: 'on the radio', pos: 'prep phr', synonym: 'broadcast by radio', uz: 'radioda' },
    { word: 'on TV', pos: 'prep phr', synonym: 'broadcast on television', uz: 'televizorda' },
    { word: 'on a computer', pos: 'prep phr', synonym: 'using a computer', uz: 'kompyuterda' },
    { word: 'certain', pos: 'word family', synonym: 'certainly, certainty', uz: 'aniq, ishonchli (va turdosh so\'zlar)' },
    { word: 'communicate', pos: 'word family', synonym: 'communication', uz: 'muloqot qilmoq (va turdosh so\'z)' },
    { word: 'connect', pos: 'word family', synonym: 'connection, disconnect', uz: 'ulamoq (va turdosh so\'zlar)' },
    { word: 'deliver', pos: 'word family', synonym: 'delivery', uz: 'yetkazib bermoq (va turdosh so\'z)' },
    { word: 'express', pos: 'word family', synonym: 'expression, expressive', uz: 'ifodalamoq (va turdosh so\'zlar)' },
    { word: 'inform', pos: 'word family', synonym: 'informative, (in)formation', uz: 'xabar bermoq (va turdosh so\'zlar)' },
    { word: 'predict', pos: 'word family', synonym: 'prediction, (un)predictable', uz: 'bashorat qilmoq (va turdosh so\'zlar)' },
    { word: 'secret', pos: 'word family', synonym: 'secretly, secrecy', uz: 'sir (va turdosh so\'zlar)' },
    { word: 'speak', pos: 'word family', synonym: 'spoke, spoken, speaker, speech', uz: 'gapirmoq (va turdosh so\'zlar)' },
    { word: 'translate', pos: 'word family', synonym: 'translation, translator', uz: 'tarjima qilmoq (va turdosh so\'zlar)' },
  ]},
  { num: 24, title: 'People and daily life', words: [
    { word: 'admit', pos: 'v', synonym: 'confess', uz: 'tan olmoq, e\'tirof etmoq' },
    { word: 'arrest', pos: 'v', synonym: 'detain', uz: 'hibsga olmoq' },
    { word: 'charity', pos: 'n', synonym: 'good cause', uz: 'xayriya' },
    { word: 'commit', pos: 'v', synonym: 'carry out (a crime)', uz: '(jinoyat) sodir etmoq' },
    { word: 'community', pos: 'n', synonym: 'local people', uz: 'jamoa, hamjamiyat' },
    { word: 'court', pos: 'n', synonym: 'tribunal', uz: 'sud' },
    { word: 'criminal', pos: 'n, adj', synonym: 'offender / illegal', uz: 'jinoyatchi / jinoiy' },
    { word: 'culture', pos: 'n', synonym: 'traditions', uz: 'madaniyat' },
    { word: 'familiar', pos: 'adj', synonym: 'well-known', uz: 'tanish' },
    { word: 'government', pos: 'n', synonym: 'administration', uz: 'hukumat' },
    { word: 'habit', pos: 'n', synonym: 'routine', uz: 'odat' },
    { word: 'identity card', pos: 'n phr', synonym: 'ID card', uz: 'shaxsni tasdiqlovchi hujjat' },
    { word: 'illegal', pos: 'adj', synonym: 'unlawful', uz: 'noqonuniy' },
    { word: 'politics', pos: 'n', synonym: 'political affairs', uz: 'siyosat' },
    { word: 'population', pos: 'n', synonym: 'inhabitants', uz: 'aholi' },
    { word: 'prison', pos: 'n', synonym: 'jail', uz: 'qamoqxona' },
    { word: 'protest', pos: 'v, n', synonym: 'demonstrate / rally', uz: 'norozilik bildirmoq / norozilik namoyishi' },
    { word: 'resident', pos: 'n', synonym: 'inhabitant', uz: 'aholi, tura oluvchi' },
    { word: 'responsible', pos: 'adj', synonym: 'in charge / accountable', uz: 'mas\'ul' },
    { word: 'rob', pos: 'v', synonym: 'steal from', uz: 'talon-taroj qilmoq' },
    { word: 'routine', pos: 'n, adj', synonym: 'regular pattern', uz: 'kundalik tartib, odatiy' },
    { word: 'schedule', pos: 'n', synonym: 'timetable', uz: 'jadval, taqvim' },
    { word: 'situation', pos: 'n', synonym: 'circumstances', uz: 'vaziyat, holat' },
    { word: 'social', pos: 'adj', synonym: 'community-related', uz: 'ijtimoiy' },
    { word: 'society', pos: 'n', synonym: 'community at large', uz: 'jamiyat' },
    { word: 'steal', pos: 'v', synonym: 'take without permission', uz: 'o\'g\'irlamoq' },
    { word: 'tradition', pos: 'n', synonym: 'custom', uz: 'an\'ana' },
    { word: 'typical', pos: 'adj', synonym: 'characteristic', uz: 'odatiy, tipik' },
    { word: 'vote', pos: 'v, n', synonym: 'cast a ballot / ballot', uz: 'ovoz bermoq / ovoz' },
    { word: 'youth club', pos: 'n phr', synonym: 'youth centre', uz: 'yoshlar klubi' },
    { word: 'break in(to)', pos: 'phrasal v', synonym: 'enter illegally', uz: 'zo\'rlab kirmoq (o\'g\'irlik uchun)' },
    { word: 'catch up (with)', pos: 'phrasal v', synonym: 'reach the same point/level as', uz: 'yetib olmoq, tenglashib olmoq' },
    { word: 'get away with', pos: 'phrasal v', synonym: 'escape punishment for', uz: 'jazosiz qolmoq' },
    { word: 'get up', pos: 'phrasal v', synonym: 'leave your bed', uz: 'turmoq (o\'rindan, uyqudan)' },
    { word: 'move in', pos: 'phrasal v', synonym: 'start living in a new house, etc', uz: 'ko\'chib kirmoq (yangi uyga)' },
    { word: 'put away', pos: 'phrasal v', synonym: 'return sth to where it belongs', uz: 'joyiga qo\'ymoq' },
    { word: 'wake up', pos: 'phrasal v', synonym: 'stop being asleep', uz: 'uyg\'onmoq' },
    { word: 'wash up', pos: 'phrasal v', synonym: 'wash plates, cups, cutlery, etc', uz: 'idish-tovoq yuvmoq' },
    { word: 'against the law', pos: 'prep phr', synonym: 'illegal', uz: 'qonunga zid' },
    { word: 'at the age of', pos: 'prep phr', synonym: 'when someone was a certain age', uz: '...yoshida' },
    { word: 'in public', pos: 'prep phr', synonym: 'in front of other people', uz: 'ommaviy joyda, hamma oldida' },
    { word: 'in response to', pos: 'prep phr', synonym: 'as a reply to', uz: 'javob tariqasida' },
    { word: 'in touch (with)', pos: 'prep phr', synonym: 'in communication (with)', uz: 'aloqada (bilan)' },
    { word: 'in your teens/twenties/etc', pos: 'prep phr', synonym: 'at that age range', uz: 'o\'smirlik/yigirma yoshlarida va h.k.' },
    { word: 'agree', pos: 'word family', synonym: 'agreement, disagree', uz: 'rozi bo\'lmoq (va turdosh so\'zlar)' },
    { word: 'belief', pos: 'word family', synonym: 'believe, (un)believable', uz: 'ishonch (va turdosh so\'zlar)' },
    { word: 'courage', pos: 'word family', synonym: 'courageous', uz: 'jasorat (va turdosh so\'z)' },
    { word: 'elect', pos: 'word family', synonym: 'election', uz: 'saylamoq (va turdosh so\'z)' },
    { word: 'equal', pos: 'word family', synonym: 'equality, unequal', uz: 'teng (va turdosh so\'zlar)' },
    { word: 'life', pos: 'word family', synonym: 'live, alive', uz: 'hayot (va turdosh so\'zlar)' },
    { word: 'nation', pos: 'word family', synonym: 'nationality, (inter)national', uz: 'millat (va turdosh so\'zlar)' },
    { word: 'peace', pos: 'word family', synonym: 'peaceful(ly)', uz: 'tinchlik (va turdosh so\'z)' },
    { word: 'shoot', pos: 'word family', synonym: 'shot, shooting', uz: 'otmoq (va turdosh so\'zlar)' },
  ]},
  { num: 27, title: 'Working and earning', words: [
    { word: 'ambition', pos: 'n', synonym: 'aspiration', uz: 'orzu, ambitsiya' },
    { word: 'application', pos: 'n', synonym: 'request form', uz: 'ariza' },
    { word: 'bank account', pos: 'n phr', synonym: 'account', uz: 'bank hisobi' },
    { word: 'boss', pos: 'n', synonym: 'manager', uz: 'boshliq' },
    { word: 'career', pos: 'n', synonym: 'profession', uz: 'karyera, kasb' },
    { word: 'colleague', pos: 'n', synonym: 'co-worker', uz: 'hamkasb' },
    { word: 'company', pos: 'n', synonym: 'business', uz: 'kompaniya' },
    { word: 'contract', pos: 'n', synonym: 'agreement', uz: 'shartnoma' },
    { word: 'department', pos: 'n', synonym: 'division', uz: 'bo\'lim' },
    { word: 'deserve', pos: 'v', synonym: 'merit', uz: 'loyiq bo\'lmoq' },
    { word: 'earn', pos: 'v', synonym: 'make money', uz: 'pul topmoq' },
    { word: 'fame', pos: 'n', synonym: 'celebrity status', uz: 'shuhrat' },
    { word: 'goal', pos: 'n', synonym: 'objective', uz: 'maqsad' },
    { word: 'impress', pos: 'v', synonym: 'make a good impression on', uz: 'taassurot qoldirmoq' },
    { word: 'income', pos: 'n', synonym: 'earnings', uz: 'daromad' },
    { word: 'industry', pos: 'n', synonym: 'sector', uz: 'sanoat, soha' },
    { word: 'interview', pos: 'v, n', synonym: 'question / meeting', uz: 'suhbat o\'tkazmoq / suhbat' },
    { word: 'leader', pos: 'n', synonym: 'head', uz: 'rahbar, yetakchi' },
    { word: 'manager', pos: 'n', synonym: 'supervisor', uz: 'menejer, boshqaruvchi' },
    { word: 'pension', pos: 'n', synonym: 'retirement income', uz: 'pensiya' },
    { word: 'poverty', pos: 'n', synonym: 'deprivation', uz: 'qashshoqlik' },
    { word: 'pressure', pos: 'n', synonym: 'stress', uz: 'bosim, stress' },
    { word: 'previous', pos: 'adj', synonym: 'earlier', uz: 'oldingi' },
    { word: 'profession', pos: 'n', synonym: 'occupation', uz: 'kasb' },
    { word: 'retire', pos: 'v', synonym: 'stop working', uz: 'nafaqaga chiqmoq' },
    { word: 'salary', pos: 'n', synonym: 'wage', uz: 'maosh' },
    { word: 'staff', pos: 'n', synonym: 'employees', uz: 'xodimlar' },
    { word: 'strike', pos: 'n', synonym: 'walkout', uz: 'ish tashlash' },
    { word: 'tax', pos: 'v, n', synonym: 'levy / duty', uz: 'soliq solmoq / soliq' },
    { word: 'wealthy', pos: 'adj', synonym: 'rich', uz: 'badavlat, boy' },
    { word: 'call off', pos: 'phrasal v', synonym: 'cancel', uz: 'bekor qilmoq' },
    { word: 'give back', pos: 'phrasal v', synonym: 'return sth you have taken/borrowed', uz: 'qaytarib bermoq' },
    { word: 'go on', pos: 'phrasal v', synonym: 'happen', uz: 'sodir bo\'lmoq, davom etmoq' },
    { word: 'put off', pos: 'phrasal v', synonym: 'delay to a later time', uz: 'kechiktirmoq' },
    { word: 'set up', pos: 'phrasal v', synonym: 'start (a business, organisation, etc)', uz: 'tashkil etmoq, ta\'sis etmoq' },
    { word: 'stay up', pos: 'phrasal v', synonym: 'go to bed late', uz: 'kech uxlamoq (uyg\'oq qolmoq)' },
    { word: 'take away', pos: 'phrasal v', synonym: 'remove', uz: 'olib ketmoq, olib tashlamoq' },
    { word: 'take over', pos: 'phrasal v', synonym: 'take control of (a business, etc)', uz: 'nazoratni qo\'lga olmoq' },
    { word: 'at the moment', pos: 'prep phr', synonym: 'currently, right now', uz: 'hozirgi vaqtda' },
    { word: 'in charge (of)', pos: 'prep phr', synonym: 'responsible for', uz: 'mas\'ul (uchun)' },
    { word: 'on business', pos: 'prep phr', synonym: 'for work purposes', uz: 'ish yuzasidan' },
    { word: 'on strike', pos: 'prep phr', synonym: 'refusing to work as a protest', uz: 'ish tashlashda' },
    { word: 'on time', pos: 'prep phr', synonym: 'punctual, not late', uz: 'vaqtida' },
    { word: 'on/off duty', pos: 'prep phr', synonym: 'working/not working (shift)', uz: 'xizmatda/xizmatdan tashqarida' },
    { word: 'assist', pos: 'word family', synonym: 'assistant, assistance', uz: 'yordam bermoq (va turdosh so\'zlar)' },
    { word: 'beg', pos: 'word family', synonym: 'beggar', uz: 'yalinmoq (va turdosh so\'z)' },
    { word: 'employ', pos: 'word family', synonym: '(un)employment, employer, employee, unemployed', uz: 'ishga olmoq (va turdosh so\'zlar)' },
    { word: 'occupy', pos: 'word family', synonym: 'occupation', uz: 'egallamoq (va turdosh so\'z)' },
    { word: 'office', pos: 'word family', synonym: 'officer, (un)official', uz: 'ofis (va turdosh so\'zlar)' },
    { word: 'safe', pos: 'word family', synonym: 'save, unsafe, safety', uz: 'xavfsiz (va turdosh so\'zlar)' },
    { word: 'succeed', pos: 'word family', synonym: 'success, (un)successful', uz: 'muvaffaqiyat qozonmoq (va turdosh so\'zlar)' },
  ]},
  { num: 30, title: 'Body and lifestyle', words: [
    { word: 'affect', pos: 'v', synonym: 'influence', uz: 'ta\'sir qilmoq' },
    { word: 'balance', pos: 'v, n', synonym: 'stabilise / equilibrium', uz: 'muvozanat saqlamoq / muvozanat' },
    { word: 'benefit', pos: 'v, n', synonym: 'gain / advantage', uz: 'foyda ko\'rmoq / foyda' },
    { word: 'breathe', pos: 'v', synonym: 'inhale and exhale', uz: 'nafas olmoq' },
    { word: 'chew', pos: 'v', synonym: 'bite and grind', uz: 'chaynamoq' },
    { word: 'chop', pos: 'v', synonym: 'cut into pieces', uz: 'maydalab to\'g\'ramoq' },
    { word: 'contain', pos: 'v', synonym: 'hold inside', uz: 'tarkibida bo\'lmoq' },
    { word: 'cough', pos: 'v, n', synonym: 'hack', uz: 'yo\'talmoq / yo\'tal' },
    { word: 'cure', pos: 'v, n', synonym: 'heal / remedy', uz: 'davolamoq / davo' },
    { word: 'exercise', pos: 'v, n', synonym: 'work out / physical activity', uz: 'mashq qilmoq / mashq' },
    { word: 'flu', pos: 'n', synonym: 'influenza', uz: 'gripp' },
    { word: 'have an operation', pos: 'v phr', synonym: 'undergo surgery', uz: 'operatsiya qildirmoq' },
    { word: 'healthy', pos: 'adj', synonym: 'fit', uz: 'sog\'lom' },
    { word: 'ignore', pos: 'v', synonym: 'disregard', uz: 'e\'tiborsiz qoldirmoq' },
    { word: 'infection', pos: 'n', synonym: 'illness', uz: 'infeksiya' },
    { word: 'ingredient', pos: 'n', synonym: 'component', uz: 'tarkibiy qism, ingredient' },
    { word: 'injury', pos: 'n', synonym: 'wound', uz: 'jarohat' },
    { word: 'limit', pos: 'v, n', synonym: 'restrict / boundary', uz: 'cheklamoq / chegara' },
    { word: 'meal', pos: 'n', synonym: 'dish', uz: 'ovqatlanish, taom' },
    { word: 'pill', pos: 'n', synonym: 'tablet', uz: 'tabletka, dori' },
    { word: 'recover', pos: 'v', synonym: 'get better', uz: 'tuzalmoq, tiklanmoq' },
    { word: 'salty', pos: 'adj', synonym: 'savoury', uz: 'sho\'r' },
    { word: 'slice', pos: 'v, n', synonym: 'cut / piece', uz: 'kesmoq / bo\'lak' },
    { word: 'sour', pos: 'adj', synonym: 'tart', uz: 'nordon' },
    { word: 'spicy', pos: 'adj', synonym: 'hot (flavour)', uz: 'achchiq (ziravorli)' },
    { word: 'stir', pos: 'v', synonym: 'mix', uz: 'aralashtirmoq' },
    { word: 'suffer', pos: 'v', synonym: 'experience pain', uz: 'azob chekmoq, aziyat chekmoq' },
    { word: 'taste', pos: 'v, n', synonym: 'try / flavour', uz: 'tatib ko\'rmoq / ta\'m' },
    { word: 'treatment', pos: 'n', synonym: 'therapy', uz: 'davolash' },
    { word: 'vitamin', pos: 'n', synonym: 'nutrient', uz: 'vitamin' },
    { word: 'cut down (on)', pos: 'phrasal v', synonym: 'do less of sth (smoking, etc)', uz: 'kamaytirmoq (odat)' },
    { word: 'fall down', pos: 'phrasal v', synonym: 'trip and fall', uz: 'yiqilmoq' },
    { word: 'get over', pos: 'phrasal v', synonym: 'recover from (an illness, etc)', uz: 'tuzalmoq, o\'zini o\'nglab olmoq' },
    { word: 'go off', pos: 'phrasal v', synonym: 'no longer be fresh', uz: 'buzilmoq (oziq- ovqat)' },
    { word: 'lie down', pos: 'phrasal v', synonym: 'start lying (on a bed, etc)', uz: 'yotmoq (dam olish uchun)' },
    { word: 'put on', pos: 'phrasal v', synonym: 'gain (weight)', uz: 'vazn qo\'shmoq' },
    { word: 'sit down', pos: 'phrasal v', synonym: '(start to) sit', uz: 'o\'tirmoq' },
    { word: 'stand up', pos: 'phrasal v', synonym: '(start to) stand', uz: 'o\'rnidan turmoq' },
    { word: 'at night', pos: 'prep phr', synonym: 'during the night', uz: 'kechasi' },
    { word: 'at risk', pos: 'prep phr', synonym: 'in danger', uz: 'xavf ostida' },
    { word: 'in addition (to)', pos: 'prep phr', synonym: 'as well as', uz: 'qo\'shimcha ravishda' },
    { word: 'in comparison to/with', pos: 'prep phr', synonym: 'compared to', uz: 'solishtirganda' },
    { word: 'in shape', pos: 'prep phr', synonym: 'physically fit', uz: 'jismoniy shaklda (formada)' },
    { word: 'on a diet', pos: 'prep phr', synonym: 'eating a controlled amount of food', uz: 'parhezda' },
    { word: 'bake', pos: 'word family', synonym: 'baker, bakery', uz: 'pishirmoq (non) (va turdosh so\'zlar)' },
    { word: 'bend', pos: 'word family', synonym: 'bent', uz: 'egmoq (va turdosh so\'z)' },
    { word: 'cook', pos: 'word family', synonym: 'cooker, cookery', uz: 'ovqat pishirmoq (va turdosh so\'zlar)' },
    { word: 'intend', pos: 'word family', synonym: 'intention, intentional', uz: 'niyat qilmoq (va turdosh so\'zlar)' },
    { word: 'jog', pos: 'word family', synonym: 'jogging, jogger', uz: 'yugurmoq (mashq uchun) (va turdosh so\'zlar)' },
    { word: 'medicine', pos: 'word family', synonym: 'medical', uz: 'dori, tibbiyot (va turdosh so\'z)' },
    { word: 'pain', pos: 'word family', synonym: 'painful, painless', uz: 'og\'riq (va turdosh so\'zlar)' },
    { word: 'reduce', pos: 'word family', synonym: 'reduction', uz: 'kamaytirmoq (va turdosh so\'z)' },
    { word: 'sense', pos: 'word family', synonym: 'sensible, sensitive', uz: 'his qilish (va turdosh so\'zlar)' },
    { word: 'weigh', pos: 'word family', synonym: 'weight', uz: 'tortmoq (vazn) (va turdosh so\'z)' },
  ]},
  { num: 33, title: 'Creating and building', words: [
    { word: 'ancient', pos: 'adj', synonym: 'very old', uz: 'qadimiy' },
    { word: 'checked', pos: 'adj', synonym: 'chequered', uz: 'katakli (matoga nisbatan)' },
    { word: 'cotton', pos: 'n', synonym: 'cotton fabric', uz: 'paxta, ip mato' },
    { word: 'create', pos: 'v', synonym: 'make', uz: 'yaratmoq' },
    { word: 'design', pos: 'v, n', synonym: 'plan / layout', uz: 'loyihalashtirmoq / dizayn' },
    { word: 'fix', pos: 'v', synonym: 'repair', uz: 'ta\'mirlamoq' },
    { word: 'fold', pos: 'v', synonym: 'bend over', uz: 'buklamoq' },
    { word: 'gallery', pos: 'n', synonym: 'exhibition hall', uz: 'galereya' },
    { word: 'improvement', pos: 'n', synonym: 'betterment', uz: 'yaxshilanish' },
    { word: 'loose', pos: 'adj', synonym: 'not tight', uz: 'bo\'sh (kiyim haqida)' },
    { word: 'maintain', pos: 'v', synonym: 'keep in good condition', uz: 'saqlab turmoq, parvarish qilmoq' },
    { word: 'match', pos: 'v', synonym: 'go with', uz: 'mos kelmoq' },
    { word: 'material', pos: 'n', synonym: 'fabric', uz: 'material, mato' },
    { word: 'notice', pos: 'v, n', synonym: 'observe / sign', uz: 'payqamoq / e\'lon' },
    { word: 'pattern', pos: 'n', synonym: 'design', uz: 'naqsh, andaza' },
    { word: 'pile', pos: 'n', synonym: 'stack', uz: 'uyum, to\'plam' },
    { word: 'practical', pos: 'adj', synonym: 'useful', uz: 'amaliy, foydali' },
    { word: 'rough', pos: 'adj', synonym: 'coarse', uz: 'g\'adir-budur' },
    { word: 'shape', pos: 'n', synonym: 'form', uz: 'shakl' },
    { word: 'silk', pos: 'n', synonym: 'silk fabric', uz: 'ipak' },
    { word: 'sleeve', pos: 'n', synonym: 'arm of a garment', uz: 'yeng' },
    { word: 'smooth', pos: 'adj', synonym: 'even', uz: 'silliq' },
    { word: 'stretch', pos: 'v', synonym: 'extend', uz: 'cho\'zmoq' },
    { word: 'striped', pos: 'adj', synonym: 'lined', uz: 'chiziqli, yo\'l-yo\'l' },
    { word: 'style', pos: 'n', synonym: 'fashion', uz: 'uslub, stil' },
    { word: 'suit', pos: 'v, n', synonym: 'look good on / formal outfit', uz: 'yarashmoq / kostyum' },
    { word: 'suitable', pos: 'adj', synonym: 'appropriate', uz: 'mos, munosib' },
    { word: 'tear', pos: 'v, n', synonym: 'rip', uz: 'yirtmoq / yirtiq' },
    { word: 'tight', pos: 'adj', synonym: 'snug', uz: 'tor, siqiq' },
    { word: 'tool', pos: 'n', synonym: 'instrument', uz: 'asbob' },
    { word: 'cut off', pos: 'phrasal v', synonym: 'completely remove by cutting', uz: 'kesib tashlamoq' },
    { word: 'do up', pos: 'phrasal v', synonym: 'button/zip up a piece of clothing', uz: 'tugmalamoq, ilgaklamoq (kiyimni)' },
    { word: 'fill up', pos: 'phrasal v', synonym: 'make sth completely full', uz: 'to\'ldirmoq' },
    { word: 'have on', pos: 'phrasal v', synonym: 'wear (a piece of clothing)', uz: 'kiyib olgan bo\'lmoq' },
    { word: 'leave out', pos: 'phrasal v', synonym: 'not include', uz: 'tushirib qoldirmoq' },
    { word: 'put on', pos: 'phrasal v', synonym: 'start wearing (a piece of clothing)', uz: 'kiymoq (kiyim)' },
    { word: 'take off', pos: 'phrasal v', synonym: 'remove (a piece of clothing)', uz: 'yechmoq (kiyim)' },
    { word: 'try on', pos: 'phrasal v', synonym: 'put on (a piece of clothing) to see how it looks and if it fits', uz: 'kiyib ko\'rmoq (o\'lchash uchun)' },
    { word: 'at the back (of)', pos: 'prep phr', synonym: 'behind', uz: 'orqasida' },
    { word: 'at the end (of)', pos: 'prep phr', synonym: 'at the finish/final part of', uz: 'oxirida' },
    { word: 'in fashion/style', pos: 'prep phr', synonym: 'currently popular', uz: 'modada' },
    { word: 'in front (of)', pos: 'prep phr', synonym: 'ahead of, before', uz: 'oldida' },
    { word: 'in the corner (of)', pos: 'prep phr', synonym: 'at the angle of a room, etc', uz: 'burchagida' },
    { word: 'out of fashion/style', pos: 'prep phr', synonym: 'no longer popular', uz: 'modadan chiqqan' },
    { word: 'art', pos: 'word family', synonym: 'artist, artistic', uz: 'san\'at (va turdosh so\'zlar)' },
    { word: 'break', pos: 'word family', synonym: 'broke, broken, (un)breakable', uz: 'sindirmoq (va turdosh so\'zlar)' },
    { word: 'compose', pos: 'word family', synonym: 'composition, composer', uz: 'bastalamoq (va turdosh so\'zlar)' },
    { word: 'exhibit', pos: 'word family', synonym: 'exhibition', uz: 'ko\'rgazmaga qo\'ymoq (va turdosh so\'z)' },
    { word: 'free', pos: 'word family', synonym: 'freedom', uz: 'erkin (va turdosh so\'z)' },
    { word: 'hand', pos: 'word family', synonym: 'handful, handle', uz: 'qo\'l (va turdosh so\'zlar)' },
    { word: 'imagine', pos: 'word family', synonym: 'imagination, imaginative', uz: 'tasavvur qilmoq (va turdosh so\'zlar)' },
    { word: 'intelligent', pos: 'word family', synonym: 'intelligence', uz: 'aqlli (va turdosh so\'z)' },
    { word: 'perfect', pos: 'word family', synonym: 'perfection, imperfect', uz: 'mukammal (va turdosh so\'zlar)' },
    { word: 'prepare', pos: 'word family', synonym: 'preparation', uz: 'tayyorlamoq (va turdosh so\'z)' },
  ]},
  { num: 36, title: 'Nature and the universe', words: [
    { word: 'amazing', pos: 'adj', synonym: 'astonishing', uz: 'ajoyib, hayratlanarli' },
    { word: 'climate', pos: 'n', synonym: 'weather pattern', uz: 'iqlim' },
    { word: 'countryside', pos: 'n', synonym: 'rural area', uz: 'qishloq joy, tabiat qo\'ynidagi hudud' },
    { word: 'environment', pos: 'n', synonym: 'surroundings', uz: 'atrof-muhit' },
    { word: 'extinct', pos: 'adj', synonym: 'no longer existing', uz: 'yo\'q bo\'lib ketgan' },
    { word: 'forecast', pos: 'v, n', synonym: 'predict / prediction', uz: 'bashorat qilmoq / bashorat' },
    { word: 'freezing', pos: 'adj', synonym: 'very cold', uz: 'juda sovuq, muzlatuvchi' },
    { word: 'global', pos: 'adj', synonym: 'worldwide', uz: 'global, dunyo miqyosidagi' },
    { word: 'heatwave', pos: 'n', synonym: 'hot spell', uz: 'issiq to\'lqin' },
    { word: 'insect', pos: 'n', synonym: 'bug', uz: 'hasharot' },
    { word: 'lightning', pos: 'n', synonym: 'electric flash', uz: 'chaqmoq' },
    { word: 'litter', pos: 'v, n', synonym: 'scatter rubbish / rubbish', uz: 'axlat tashlamoq / axlat' },
    { word: 'local', pos: 'adj', synonym: 'nearby', uz: 'mahalliy' },
    { word: 'locate', pos: 'v', synonym: 'find the position of', uz: 'joylashtirmoq, topmoq' },
    { word: 'mammal', pos: 'n', synonym: 'warm-blooded animal', uz: 'sut emizuvchi' },
    { word: 'mild', pos: 'adj', synonym: 'gentle', uz: 'mo\'\'tadil, yumshoq' },
    { word: 'name', pos: 'v, n', synonym: 'call / title', uz: 'nom bermoq / nom' },
    { word: 'origin', pos: 'n', synonym: 'source', uz: 'kelib chiqishi, manba' },
    { word: 'planet', pos: 'n', synonym: 'world', uz: 'sayyora' },
    { word: 'preserve', pos: 'v', synonym: 'protect and maintain', uz: 'asrab qolmoq, saqlamoq' },
    { word: 'recycle', pos: 'v', synonym: 'reuse materials', uz: 'qayta ishlamoq' },
    { word: 'reptile', pos: 'n', synonym: 'cold-blooded animal', uz: 'sudralib yuruvchi' },
    { word: 'rescue', pos: 'v, n', synonym: 'save', uz: 'qutqarmoq / qutqaruv' },
    { word: 'satellite', pos: 'n', synonym: 'orbiting device', uz: 'sun\'iy yo\'ldosh' },
    { word: 'shower', pos: 'n', synonym: 'brief rain', uz: 'yomg\'ir yog\'ishi (qisqa)' },
    { word: 'solar system', pos: 'n phr', synonym: 'planetary system', uz: 'quyosh sistemasi' },
    { word: 'species', pos: 'n', synonym: 'type of organism', uz: 'tur (biologik)' },
    { word: 'thunder', pos: 'n', synonym: 'loud rumble', uz: 'momaqaldiroq' },
    { word: 'wild', pos: 'adj', synonym: 'untamed', uz: 'yovvoyi' },
    { word: 'wildlife', pos: 'n', synonym: 'fauna', uz: 'yovvoyi tabiat' },
    { word: 'blow up', pos: 'phrasal v', synonym: 'explode', uz: 'portlamoq' },
    { word: 'build up', pos: 'phrasal v', synonym: 'increase', uz: 'ortmoq, yig\'ilmoq' },
    { word: 'clear up', pos: 'phrasal v', synonym: 'tidy', uz: 'tozalamoq, yig\'ishtirmoq' },
    { word: 'go out', pos: 'phrasal v', synonym: 'stop burning', uz: 'o\'chmoq (olov)' },
    { word: 'keep out', pos: 'phrasal v', synonym: 'prevent from entering', uz: 'kiritmaslik, to\'sib qo\'ymoq' },
    { word: 'put down', pos: 'phrasal v', synonym: 'stop holding', uz: 'qo\'ymoq (ushlab turgan narsani)' },
    { word: 'put out', pos: 'phrasal v', synonym: 'make something stop burning', uz: 'o\'chirmoq (olovni)' },
    { word: 'put up', pos: 'phrasal v', synonym: 'put something on a wall (eg, a picture)', uz: 'osib qo\'ymoq (devorga)' },
    { word: 'at most', pos: 'prep phr', synonym: 'not more than', uz: 'ko\'pi bilan' },
    { word: 'at the top/bottom (of)', pos: 'prep phr', synonym: 'at the highest/lowest point of', uz: 'yuqorisida/pastida' },
    { word: 'in the beginning', pos: 'prep phr', synonym: 'at first', uz: 'boshida, dastlab' },
    { word: 'in the distance', pos: 'prep phr', synonym: 'far away but visible', uz: 'uzoqda (ko\'rinib turgan)' },
    { word: 'in total', pos: 'prep phr', synonym: 'altogether', uz: 'jami, umumiy hisobda' },
    { word: 'on top (of)', pos: 'prep phr', synonym: 'on the upper surface of', uz: 'ustida' },
    { word: 'centre', pos: 'word family', synonym: 'central', uz: 'markaz (va turdosh so\'z)' },
    { word: 'circle', pos: 'word family', synonym: 'circular', uz: 'aylana (va turdosh so\'z)' },
    { word: 'danger', pos: 'word family', synonym: 'dangerous', uz: 'xavf (va turdosh so\'z)' },
    { word: 'deep', pos: 'word family', synonym: 'deeply, depth', uz: 'chuqur (va turdosh so\'zlar)' },
    { word: 'destroy', pos: 'word family', synonym: 'destruction, destructive', uz: 'vayron qilmoq (va turdosh so\'zlar)' },
    { word: 'fog', pos: 'word family', synonym: 'foggy', uz: 'tuman (va turdosh so\'z)' },
    { word: 'garden', pos: 'word family', synonym: 'gardener, gardening', uz: 'bog\' (va turdosh so\'zlar)' },
    { word: 'invade', pos: 'word family', synonym: 'invasion, invader', uz: 'bosib olmoq (va turdosh so\'zlar)' },
    { word: 'nature', pos: 'word family', synonym: 'natural, naturally', uz: 'tabiat (va turdosh so\'zlar)' },
    { word: 'pollute', pos: 'word family', synonym: 'pollution, polluted', uz: 'ifloslantirmoq (va turdosh so\'zlar)' },
  ]},
  { num: 39, title: 'Laughing and crying', words: [
    { word: 'amusing', pos: 'adj', synonym: 'funny', uz: 'kulgili, qiziq' },
    { word: 'annoy', pos: 'v', synonym: 'irritate', uz: 'jahlini chiqarmoq, bezovta qilmoq' },
    { word: 'attitude', pos: 'n', synonym: 'outlook', uz: 'munosabat, qarash' },
    { word: 'bad-tempered', pos: 'adj', synonym: 'irritable', uz: 'achchiq feyilli, jahldor' },
    { word: 'behave', pos: 'v', synonym: 'act', uz: 'o\'zini tutmoq' },
    { word: 'bully', pos: 'v, n', synonym: 'intimidate / tormentor', uz: 'qo\'rqitmoq, xo\'rlamoq / xo\'rlovchi' },
    { word: 'calm', pos: 'adj', synonym: 'relaxed', uz: 'xotirjam, sokin' },
    { word: 'celebrate', pos: 'v', synonym: 'mark an occasion', uz: 'nishonlamoq' },
    { word: 'character', pos: 'n', synonym: 'personality', uz: 'xarakter, xususiyat' },
    { word: 'depressed', pos: 'adj', synonym: 'low', uz: 'tushkunlikka tushgan' },
    { word: 'embarrassing', pos: 'adj', synonym: 'awkward', uz: 'noqulay, uyat' },
    { word: 'emotion', pos: 'n', synonym: 'feeling', uz: 'his-tuyg\'u' },
    { word: 'enthusiastic', pos: 'adj', synonym: 'eager', uz: 'ishtiyoqli' },
    { word: 'feeling', pos: 'n', synonym: 'emotion', uz: 'tuyg\'u, his' },
    { word: 'glad', pos: 'adj', synonym: 'pleased', uz: 'xursand' },
    { word: 'hurt', pos: 'v, adj', synonym: 'injure / upset', uz: 'og\'ritmoq / xafa bo\'lgan' },
    { word: 'miserable', pos: 'adj', synonym: 'unhappy', uz: 'baxtsiz, g\'amgin' },
    { word: 'naughty', pos: 'adj', synonym: 'badly-behaved', uz: 'shumtaka, yaramas (bolalar haqida)' },
    { word: 'noisy', pos: 'adj', synonym: 'loud', uz: 'shovqinli' },
    { word: 'polite', pos: 'adj', synonym: 'courteous', uz: 'xushmuomala, odobli' },
    { word: 'react', pos: 'v', synonym: 'respond', uz: 'munosabat bildirmoq, reaksiya berish' },
    { word: 'regret', pos: 'v, n', synonym: 'be sorry about / remorse', uz: 'afsuslanmoq / afsus' },
    { word: 'ridiculous', pos: 'adj', synonym: 'absurd', uz: 'kulgili, ahmoqona' },
    { word: 'romantic', pos: 'adj', synonym: 'loving', uz: 'romantik' },
    { word: 'rude', pos: 'adj', synonym: 'impolite', uz: 'qo\'pol, beodob' },
    { word: 'sense of humour', pos: 'n phr', synonym: 'wit', uz: 'hazil tuyg\'usi' },
    { word: 'shy', pos: 'adj', synonym: 'timid', uz: 'uyatchan' },
    { word: 'stress', pos: 'n', synonym: 'tension', uz: 'stress, zo\'riqish' },
    { word: 'tell a joke', pos: 'v phr', synonym: 'joke around', uz: 'latifa aytmoq' },
    { word: 'upset', pos: 'v, adj', synonym: 'distress / unhappy', uz: 'xafa qilmoq / xafa bo\'lgan' },
    { word: 'calm down', pos: 'phrasal v', synonym: 'become/make calmer', uz: 'tinchlanmoq, tinchlantirmoq' },
    { word: 'cheer up', pos: 'phrasal v', synonym: 'become/make happier', uz: 'ko\'ngilni ko\'tarmoq' },
    { word: 'come on', pos: 'phrasal v', synonym: 'be quicker', uz: 'tezroq bo\'l, kel' },
    { word: 'go on', pos: 'phrasal v', synonym: 'continue happening or doing sth', uz: 'davom etmoq' },
    { word: 'hang on', pos: 'phrasal v', synonym: 'wait', uz: 'kutib turmoq' },
    { word: 'run away (from)', pos: 'phrasal v', synonym: 'escape by running', uz: 'qochib ketmoq' },
    { word: 'shut up', pos: 'phrasal v', synonym: 'stop talking, stop making a noise', uz: 'jim bo\'lmoq' },
    { word: 'speak up', pos: 'phrasal v', synonym: 'talk more loudly so sb can hear you', uz: 'baland ovozda gapirmoq' },
    { word: 'at first', pos: 'prep phr', synonym: 'initially', uz: 'dastlab' },
    { word: 'at least', pos: 'prep phr', synonym: 'not less than', uz: 'kamida' },
    { word: 'at times', pos: 'prep phr', synonym: 'sometimes', uz: 'ba\'zida' },
    { word: 'in secret', pos: 'prep phr', synonym: 'secretly', uz: 'maxfiy ravishda' },
    { word: 'in spite of', pos: 'prep phr', synonym: 'despite', uz: '...ga qaramay' },
    { word: 'in tears', pos: 'prep phr', synonym: 'crying', uz: 'ko\'z yosh to\'kib' },
    { word: 'bore', pos: 'word family', synonym: 'boring, bored', uz: 'zeriktirmoq (va turdosh so\'zlar)' },
    { word: 'comedy', pos: 'word family', synonym: 'comedian', uz: 'komediya (va turdosh so\'z)' },
    { word: 'energy', pos: 'word family', synonym: 'energetic', uz: 'energiya (va turdosh so\'z)' },
    { word: 'excite', pos: 'word family', synonym: 'excitement, exciting, excited', uz: 'hayajonlantirmoq (va turdosh so\'zlar)' },
    { word: 'feel', pos: 'word family', synonym: 'felt, feeling(s)', uz: 'his qilmoq (va turdosh so\'zlar)' },
    { word: 'happy', pos: 'word family', synonym: 'unhappy, (un)happiness', uz: 'baxtli (va turdosh so\'zlar)' },
    { word: 'hate', pos: 'word family', synonym: 'hatred', uz: 'nafratlanmoq (va turdosh so\'z)' },
    { word: 'noise', pos: 'word family', synonym: 'noisy, noisily', uz: 'shovqin (va turdosh so\'zlar)' },
    { word: 'sympathy', pos: 'word family', synonym: 'sympathise, sympathetic', uz: 'hamdardlik (va turdosh so\'zlar)' },
  ]},
  { num: 42, title: 'Problems and solutions', words: [
    { word: 'accident', pos: 'n', synonym: 'mishap', uz: 'tasodifiy hodisa, avariya' },
    { word: 'assume', pos: 'v', synonym: 'presume', uz: 'faraz qilmoq' },
    { word: 'cause', pos: 'v, n', synonym: 'bring about / reason', uz: 'sabab bo\'lmoq / sabab' },
    { word: 'claim', pos: 'v', synonym: 'assert', uz: 'da\'vo qilmoq' },
    { word: 'complain', pos: 'v', synonym: 'protest about', uz: 'shikoyat qilmoq' },
    { word: 'convince', pos: 'v', synonym: 'persuade', uz: 'ishontirmoq' },
    { word: 'criticise', pos: 'v', synonym: 'find fault with', uz: 'tanqid qilmoq' },
    { word: 'deny', pos: 'v', synonym: 'reject as false', uz: 'rad etmoq, inkor qilmoq' },
    { word: 'doubt', pos: 'v, n', synonym: 'question / uncertainty', uz: 'shubha qilmoq / shubha' },
    { word: 'encourage', pos: 'v', synonym: 'motivate', uz: 'rag\'batlantirmoq' },
    { word: 'get rid of', pos: 'v phr', synonym: 'dispose of', uz: 'qutulmoq, tashlab yubormoq' },
    { word: 'gossip', pos: 'v, n', synonym: 'chat about others', uz: 'g\'iybat qilmoq / g\'iybat' },
    { word: 'ideal', pos: 'adj', synonym: 'perfect', uz: 'ideal, mukammal' },
    { word: 'insult', pos: 'v, n', synonym: 'offend / offensive remark', uz: 'haqorat qilmoq / haqorat' },
    { word: 'investigate', pos: 'v', synonym: 'look into', uz: 'tekshirmoq, tergov qilmoq' },
    { word: 'negative', pos: 'adj', synonym: 'pessimistic', uz: 'salbiy' },
    { word: 'positive', pos: 'adj', synonym: 'optimistic', uz: 'ijobiy' },
    { word: 'praise', pos: 'v, n', synonym: 'compliment', uz: 'maqtamoq / maqtov' },
    { word: 'pretend', pos: 'v', synonym: 'act as if', uz: 'o\'zini ... qilib ko\'rsatmoq' },
    { word: 'refuse', pos: 'v', synonym: 'decline', uz: 'rad etmoq' },
    { word: 'result', pos: 'v, n', synonym: 'lead to / outcome', uz: 'natijalanmoq / natija' },
    { word: 'rumour', pos: 'n', synonym: 'unconfirmed report', uz: 'mish-mish' },
    { word: 'sensible', pos: 'adj', synonym: 'reasonable', uz: 'aqlli, oqilona' },
    { word: 'serious', pos: 'adj', synonym: 'grave', uz: 'jiddiy' },
    { word: 'spare', pos: 'adj', synonym: 'extra', uz: 'zaxira, ortiqcha' },
    { word: 'theory', pos: 'n', synonym: 'hypothesis', uz: 'nazariya' },
    { word: 'thought', pos: 'n', synonym: 'idea', uz: 'fikr, o\'y' },
    { word: 'warn', pos: 'v', synonym: 'caution', uz: 'ogohlantirmoq' },
    { word: 'hang up', pos: 'phrasal v', synonym: 'put clothes in a wardrobe, etc', uz: 'osib qo\'ymoq (kiyimni)' },
    { word: 'pick up', pos: 'phrasal v', synonym: 'lift something from the floor, a table, etc', uz: 'ko\'tarib olmoq' },
    { word: 'put back', pos: 'phrasal v', synonym: 'return something to where it was', uz: 'joyiga qaytarib qo\'ymoq' },
    { word: 'run out (of)', pos: 'phrasal v', synonym: 'not have any left', uz: 'tugab qolmoq' },
    { word: 'share out', pos: 'phrasal v', synonym: 'give a part of sth to a group of people', uz: 'bo\'lib bermoq' },
    { word: 'sort out', pos: 'phrasal v', synonym: 'solve a problem', uz: 'hal qilmoq (muammoni)' },
    { word: 'watch out', pos: 'phrasal v', synonym: 'be careful', uz: 'ehtiyot bo\'lmoq' },
    { word: 'work out', pos: 'phrasal v', synonym: 'find the solution to a problem, etc', uz: 'yechimini topmoq' },
    { word: 'by accident/mistake', pos: 'prep phr', synonym: 'unintentionally', uz: 'tasodifan, bilmasdan' },
    { word: 'in a mess', pos: 'prep phr', synonym: 'untidy, disorganised', uz: 'tartibsiz holatda' },
    { word: 'in danger (of)', pos: 'prep phr', synonym: 'at risk (of)', uz: 'xavf ostida' },
    { word: 'in my view', pos: 'prep phr', synonym: 'in my opinion', uz: 'mening nazarimda' },
    { word: 'in trouble', pos: 'prep phr', synonym: 'in a difficult situation', uz: 'muammoda, balo- qazoda' },
    { word: 'under pressure', pos: 'prep phr', synonym: 'experiencing stress', uz: 'bosim ostida' },
    { word: 'advice', pos: 'word family', synonym: 'advise, adviser', uz: 'maslahat (va turdosh so\'zlar)' },
    { word: 'confuse', pos: 'word family', synonym: 'confused, confusion', uz: 'chalkashtirmoq (va turdosh so\'zlar)' },
    { word: 'except', pos: 'word family', synonym: 'exception', uz: 'bundan tashqari (va turdosh so\'z)' },
    { word: 'help', pos: 'word family', synonym: '(un)helpful, helpless', uz: 'yordam (va turdosh so\'zlar)' },
    { word: 'luck', pos: 'word family', synonym: '(un)lucky, (un)luckily', uz: 'omad (va turdosh so\'zlar)' },
    { word: 'prefer', pos: 'word family', synonym: 'preference, preferable', uz: 'afzal ko\'rmoq (va turdosh so\'zlar)' },
    { word: 'recommend', pos: 'word family', synonym: 'recommendation', uz: 'tavsiya qilmoq (va turdosh so\'z)' },
    { word: 'solve', pos: 'word family', synonym: 'solution', uz: 'hal qilmoq (va turdosh so\'z)' },
    { word: 'suggest', pos: 'word family', synonym: 'suggestion', uz: 'taklif qilmoq (va turdosh so\'z)' },
  ]},
];

export default VOCAB_RACE_UNITS;