/**
 * Word Duel questions: quick vocabulary for B1–C1 — meanings, opposites,
 * collocations, prepositions and word forms. The right answer is always
 * written first here; the server shuffles the options before sending them.
 */

const Q = (text, right, ...wrong) => ({ text, options: [right, ...wrong] });

const RAW = [
  // Closest meaning
  Q('Closest meaning: "reluctant"', 'unwilling', 'eager', 'careful', 'angry'),
  Q('Closest meaning: "enormous"', 'huge', 'tiny', 'strange', 'heavy'),
  Q('Closest meaning: "rapid"', 'fast', 'rare', 'rough', 'quiet'),
  Q('Closest meaning: "purchase"', 'buy', 'sell', 'borrow', 'repair'),
  Q('Closest meaning: "assist"', 'help', 'insist', 'avoid', 'allow'),
  Q('Closest meaning: "obtain"', 'get', 'lose', 'hide', 'share'),
  Q('Closest meaning: "vital"', 'essential', 'optional', 'visible', 'violent'),
  Q('Closest meaning: "require"', 'need', 'refuse', 'repeat', 'return'),
  Q('Closest meaning: "significant"', 'important', 'silent', 'similar', 'simple'),
  Q('Closest meaning: "diverse"', 'varied', 'divided', 'difficult', 'dull'),
  Q('Closest meaning: "decline" (numbers)', 'fall', 'rise', 'stay', 'double'),
  Q('Closest meaning: "boost"', 'increase', 'reduce', 'delay', 'measure'),
  Q('Closest meaning: "tackle" (a problem)', 'deal with', 'ignore', 'create', 'describe'),
  Q('Closest meaning: "brief"', 'short', 'bright', 'broad', 'brave'),
  Q('Closest meaning: "frequently"', 'often', 'rarely', 'freely', 'quickly'),
  Q('Closest meaning: "accurate"', 'correct', 'quick', 'careless', 'cheap'),
  Q('Closest meaning: "commence"', 'begin', 'finish', 'comment', 'compare'),
  Q('Closest meaning: "affluent"', 'rich', 'poor', 'famous', 'fluent'),
  Q('Closest meaning: "hazardous"', 'dangerous', 'lucky', 'harmless', 'hidden'),
  Q('Closest meaning: "attempt"', 'try', 'attend', 'attack', 'achieve'),
  Q('Closest meaning: "adequate"', 'enough', 'excellent', 'extra', 'exact'),
  Q('Closest meaning: "consequence"', 'result', 'reason', 'condition', 'question'),
  Q('Closest meaning: "crucial"', 'extremely important', 'cruel', 'unclear', 'common'),
  Q('Closest meaning: "reside"', 'live', 'rest', 'resign', 'return'),
  Q('Closest meaning: "anticipate"', 'expect', 'forget', 'celebrate', 'regret'),
  Q('Closest meaning: "drawback"', 'disadvantage', 'benefit', 'drawing', 'delay'),
  Q('Closest meaning: "thrilled"', 'very happy', 'very tired', 'scared', 'bored'),
  Q('Closest meaning: "exhausted"', 'very tired', 'excited', 'angry', 'hungry'),
  Q('Closest meaning: "wealthy"', 'rich', 'healthy', 'wise', 'lonely'),
  Q('Closest meaning: "occupation"', 'job', 'hobby', 'holiday', 'opinion'),

  // Opposites
  Q('Opposite of "ancient"', 'modern', 'old', 'huge', 'famous'),
  Q('Opposite of "generous"', 'mean', 'kind', 'general', 'gentle'),
  Q('Opposite of "increase"', 'decrease', 'improve', 'include', 'expand'),
  Q('Opposite of "temporary"', 'permanent', 'modern', 'quick', 'busy'),
  Q('Opposite of "shallow"', 'deep', 'narrow', 'wide', 'high'),
  Q('Opposite of "accept"', 'reject', 'receive', 'agree', 'expect'),
  Q('Opposite of "rural"', 'urban', 'royal', 'natural', 'rare'),
  Q('Opposite of "optimistic"', 'pessimistic', 'realistic', 'optional', 'hopeful'),
  Q('Opposite of "scarce"', 'plentiful', 'scary', 'rare', 'expensive'),
  Q('Opposite of "guilty"', 'innocent', 'sorry', 'honest', 'brave'),
  Q('Opposite of "arrive"', 'depart', 'reach', 'stay', 'appear'),
  Q('Opposite of "minimum"', 'maximum', 'minority', 'medium', 'majority'),
  Q('Opposite of "lend"', 'borrow', 'give', 'spend', 'send'),
  Q('Opposite of "succeed"', 'fail', 'follow', 'suggest', 'win'),
  Q('Opposite of "complicated"', 'simple', 'completed', 'difficult', 'correct'),
  Q('Opposite of "voluntary"', 'compulsory', 'valuable', 'free', 'unpaid'),
  Q('Opposite of "expand"', 'shrink', 'explain', 'grow', 'spread'),
  Q('Opposite of "transparent"', 'opaque', 'clear', 'honest', 'visible'),

  // Collocations
  Q('___ a decision', 'make', 'do', 'say', 'have'),
  Q('___ homework', 'do', 'make', 'take', 'give'),
  Q('___ a mistake', 'make', 'do', 'take', 'play'),
  Q('___ a photo', 'take', 'make', 'do', 'bring'),
  Q('___ an effort', 'make', 'do', 'take', 'put'),
  Q('___ attention (to)', 'pay', 'do', 'make', 'take'),
  Q('___ a risk', 'take', 'make', 'do', 'win'),
  Q('___ progress', 'make', 'do', 'take', 'have'),
  Q('___ research', 'do', 'make', 'take', 'play'),
  Q('___ a role (in)', 'play', 'make', 'do', 'take'),
  Q('___ traffic (a lot of cars)', 'heavy', 'strong', 'fat', 'thick'),
  Q('___ rain (a lot of rain)', 'heavy', 'strong', 'big', 'hard'),
  Q('___ coffee (not weak)', 'strong', 'heavy', 'hard', 'thick'),
  Q('___ a promise', 'keep', 'hold', 'save', 'stay'),
  Q('___ a speech', 'give', 'say', 'tell', 'talk'),
  Q('___ the truth', 'tell', 'say', 'speak', 'talk'),
  Q('___ a crime', 'commit', 'make', 'do', 'play'),
  Q('___ an exam (be successful)', 'pass', 'take', 'make', 'win'),
  Q('___ a conclusion', 'reach', 'finish', 'get', 'take'),
  Q('raise ___ (make people know)', 'awareness', 'knowing', 'attention', 'notice'),
  Q('a ___ of opinion', 'difference', 'different', 'differ', 'difficulty'),
  Q('___ a goal (achieve it)', 'reach', 'arrive', 'come', 'go'),

  // Prepositions
  Q('interested ___ music', 'in', 'on', 'at', 'about'),
  Q('depend ___ the weather', 'on', 'of', 'from', 'at'),
  Q('good ___ maths', 'at', 'in', 'on', 'with'),
  Q('afraid ___ spiders', 'of', 'from', 'about', 'with'),
  Q('responsible ___ the project', 'for', 'of', 'about', 'to'),
  Q('married ___ a doctor', 'to', 'with', 'on', 'for'),
  Q('arrive ___ Tashkent', 'in', 'to', 'at', 'on'),
  Q('arrive ___ the airport', 'at', 'to', 'in', 'on'),
  Q('similar ___ his brother', 'to', 'with', 'as', 'for'),
  Q('different ___ the others', 'from', 'of', 'with', 'at'),
  Q('proud ___ my family', 'of', 'for', 'with', 'about'),
  Q('the reason ___ the delay', 'for', 'of', 'to', 'about'),
  Q('an increase ___ prices', 'in', 'of', 'on', 'at'),
  Q('the key ___ success', 'to', 'of', 'for', 'in'),
  Q('an impact ___ society', 'on', 'to', 'for', 'in'),
  Q('apply ___ a job', 'for', 'to', 'on', 'at'),
  Q('___ the other hand', 'on', 'in', 'at', 'by'),
  Q('___ my opinion', 'in', 'on', 'at', 'for'),
  Q('keen ___ football', 'on', 'in', 'at', 'of'),
  Q('capable ___ winning', 'of', 'to', 'for', 'in'),

  // Word forms
  Q('Noun of "decide"', 'decision', 'decisive', 'deciding', 'decidedly'),
  Q('Noun of "develop"', 'development', 'developful', 'developing', 'developed'),
  Q('Adjective of "danger"', 'dangerous', 'dangerly', 'dangered', 'dangerful'),
  Q('Adjective of "success"', 'successful', 'succeeding', 'successous', 'successly'),
  Q('Noun of "able"', 'ability', 'ableness', 'enable', 'ably'),
  Q('Opposite adjective of "responsible"', 'irresponsible', 'unresponsible', 'disresponsible', 'inresponsible'),
  Q('Opposite adjective of "possible"', 'impossible', 'unpossible', 'inpossible', 'dispossible'),
  Q('Opposite adjective of "honest"', 'dishonest', 'unhonest', 'inhonest', 'imhonest'),
  Q('Noun of "improve"', 'improvement', 'improval', 'improvation', 'improvance'),
  Q('Adverb of "careful"', 'carefully', 'carefuly', 'carefulness', 'caringly'),
  Q('Noun of "pollute"', 'pollution', 'pollutement', 'pollutance', 'pollutation'),
  Q('Noun of "argue"', 'argument', 'arguement', 'arguance', 'arguation'),
  Q('Past form: "rise"', 'rose', 'rised', 'risen', 'rosen'),
  Q('Past participle: "write"', 'written', 'wrote', 'writed', 'writen'),
  Q('Past participle: "choose"', 'chosen', 'chose', 'choosed', 'choosen'),
  Q('Past form: "catch"', 'caught', 'catched', 'cought', 'catch'),

  // Linkers
  Q('Adds a contrast: "It was cheap; ___, it broke quickly."', 'however', 'therefore', 'moreover', 'for example'),
  Q('Shows a result: "It rained; ___, the match was cancelled."', 'therefore', 'however', 'although', 'whereas'),
  Q('Adds a point: "It is cheap. ___, it is fast."', 'Moreover', 'However', 'Instead', 'Otherwise'),
  Q('"___ it was late, we kept working."', 'Although', 'Despite', 'However', 'Because of'),
  Q('"___ the rain, we went out."', 'Despite', 'Although', 'However', 'Even'),
  Q('"Some like tea, ___ others prefer coffee."', 'whereas', 'because', 'so that', 'unless'),
  Q('"Take an umbrella ___ it rains."', 'in case', 'so that', 'unless', 'whereas'),
  Q('"You will fail ___ you study."', 'unless', 'if', 'because', 'although')
];

export const DUEL_QUESTIONS = RAW.map((q, i) => ({ id: `wd${i + 1}`, ...q }));
export default DUEL_QUESTIONS;
